### ISSUE TITLE
Error pops up while renaming attachments

### ISSUE THREAD

**Issue by jaimysimon** [neetozone/neeto-editor#1013]
The renaming operation is successful though. Once I reload it, the new name is displayed, but initially this error pops up.

neetoPlanner:
<img width="1440" alt="Screenshot 2024-02-27 at 11 47 29 AM" src="https://github.com/bigbinary/neeto-editor/assets/56317326/224ba88a-7be8-493c-add0-8ef0d596fcdb">

neetoKB:
<img width="1438" alt="Screenshot 2024-02-27 at 11 47 52 AM" src="https://github.com/bigbinary/neeto-editor/assets/56317326/25d6960a-557e-403b-a3e3-3c568bce7d9c">

**Comment by gaagul** [comment]
@gaagul _a
