### ISSUE TITLE
Editor content is empty initially but on typing something and clearing the content adds redundant `<p></p>` tags

### ISSUE THREAD

**Issue by vivek-viswam-rv** [neetozone/neeto-editor#1021]
Initially, the editor content internally is '', i.e. empty.
If I write something and clear the editor content using backspace, `<p></p>`, this is the content internally. But to the end user, the content is '', i.e. empty.

cc: @AbhayVAshokan @josephmathew900

**Comment by AbhayVAshokan** [comment]
@vivek-viswam-rv can you please provide more context into where this is used? 

- To add validations please use the `isEditorEmpty` method in the Yup validation schema.

Ideally, the default value for neetoEditor should be `<p></p>` and not an empty string. We have added a warning in the Chrome console whenever '' is used.

discussion _t
