### ISSUE TITLE
Better experience with images

### ISSUE THREAD

**Issue by karthiknmenon** [neetozone/neeto-editor#103]
@amaldinesh7 _a 

Please check the [loom video](https://www.loom.com/share/9eb4e8e4ef4b4f32b2fa8ea472bfccaf) attached. I feel these small enhancements will enrich the writing experience in neetoKb or wherever in the future we have the same use case. 
Please let me know your thoughts on this. 

enhancement _t discussion _t

cc: @AbhayVAshokan, @labeebklatif, @goutham-subramanyam

**Comment by karthiknmenon** [comment]
@AbhayVAshokan @goutham-subramanyam Let's start digging into this now that we have image upload and unsplash integration ready.

**Comment by AbhayVAshokan** [comment]
The ability to align images is very handy. Currently, the size of the image depends on its dimensions, and text does not wrap around it. 

The options available on LinkedIn are similar to those in Medium. Adding a screenshot for reference.
![LinkedIn image alignment](https://user-images.githubusercontent.com/35297280/147722500-e336a063-ff13-4ddd-ab7d-190b7727a3aa.png)
