### ISSUE TITLE
paragraph => text 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#1032]
https://neerajsingh0101.neetorecord.com/watch/622b997f-53af-4167-95f3-13aa99173802

https://www.youtube.com/watch?v=-jX1ynqvsz4

discussion _t

**Comment by gaagul** [comment]
I have gone through a few similar products which has option to select text style from dropdowns, Following are the general terms they use


1  Tiptap documentation and templates

<img width="750" alt="Screenshot 2024-04-02 at 11 42 22 AM" src="https://github.com/bigbinary/neeto-editor/assets/70290286/69abacef-1a73-4eb4-9943-ba9215a01564">

...

2 Substack

<img width="968" alt="Screenshot 2024-04-02 at 11 43 52 AM" src="https://github.com/bigbinary/neeto-editor/assets/70290286/2c84f6b7-02d3-4868-9e75-82c093e02a65">

...

3 Google docs

<img width="750" alt="Screenshot 2024-04-02 at 11 42 40 AM" src="https://github.com/bigbinary/neeto-editor/assets/70290286/76adc3c7-4382-4eae-9e95-93681a28388b">

...

4 Notion

<img width="968" alt="Screenshot 2024-04-02 at 11 45 14 AM" src="https://github.com/bigbinary/neeto-editor/assets/70290286/b7b58b3c-876d-401f-b346-7c6fd403468f">

5 LinkedIn

![Screenshot 2024-04-02 at 12 44 09 PM](https://github.com/bigbinary/neeto-editor/assets/35297280/aa6c29f9-7021-4711-b1a5-fedc77351f25)

**Comment by AbhayVAshokan** [comment]
@gaagul thanks for looking into this.

@neerajsingh0101 there is no clear convention on which should be used. If "Paragraph" is too confusing, "Text", or "Normal text" are pretty good candidates.

**Comment by neerajsingh0101** [comment]
I think "Normal text" is pretty clear. Let's roll with it.
