### ISSUE TITLE
Better icon for table 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#1033]
Watch the end of the video https://www.youtube.com/watch?v=-jX1ynqvsz4

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
There is an icon that we use for table view in neetoRecord, should we switch to it or ask ui team for a new icon,

![Image](https://github.com/bigbinary/neeto-editor/assets/70290286/ff806dcc-4927-44dd-bead-26d663adf550)

Please let me know your thoughts on using the above mentioned icon @neerajsingh0101 @AbhayVAshokan

**Comment by neerajsingh0101** [comment]
@gaagul Let's use the icon the neetoRecord team is using.
