### ISSUE TITLE
Check build failure

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1045]
https://neeto-engineering.neetodeploy.com/apps/neeto-editor-production/activity/build/7a83d7ce-b697-498f-b1e2-dc1414a2e432

@gaagul _a

**Comment by gaagul** [comment]
Closing the issue since the fix was added in https://github.com/bigbinary/neeto-editor/pull/1051 PR along with fixing the conflicts in storybook.
