### ISSUE TITLE
[neeto-desk-frontend/staging] TypeError: Cannot read properties of undefined (reading 'create') 

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1074]
Ref: https://github.com/bigbinary/neeto-desk-web/issues/19298

**Comment by AbhayVAshokan** [comment]
Raised in 1.31.3-beta.1. Fixed by https://github.com/bigbinary/neeto-editor/pull/1065/commits/651d00257298c8d4081c00f75db312bcfab567ea.
