### ISSUE TITLE
Pasting link in the editor causes an error

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1077]
https://github.com/bigbinary/neeto-desk-web/issues/19328

---

Paste the following content into the editor
```
http://google.com/ hello world
```

This will throw the error

```
Uncaught RangeError: Can not convert <"http://google.com hello world"> to a Fragment (looks like multiple versions of prosemirror-model were loaded)
    at Fragment.from (index.js:371:15)
    at NodeType.create (index.js:2158:66)
    at Node$1.fromJSON (index.js:1638:43)
    at eval (index.js:5641:23)
    at Array.forEach (<anonymous>)
    at clipboardTextParser (index.js:5631:10)
    at eval (index.js:2781:64)
    at EditorView.someProp (index.js:5411:42)
    at parseFromClipboard (index.js:2781:27)
    at doPaste (index.js:3579:17)
```

@AbhayVAshokan _a
bug _t

**Comment by sandip-mane** [comment]
@AbhayVAshokan any updates on this? We are getting this issue in production frequently.
Ref: https://app.honeybadger.io/projects/94821/faults/107058650

**Comment by AbhayVAshokan** [comment]
**Update**

The issue is caused by the custom clipboardTextParser added within neetoEditor.

https://github.com/bigbinary/neeto-editor/blob/53a639e3939d662c7ded985fb85c9c2afedbaac3/src/components/Editor/utils.js#L24-L40

Removing this custom logic can fix the issue. But the issue is only reproducible only within the beta version of neetoEditor due to internal dependency issues. I had deprioritized the issue to M10 since it does not block the user in any way. I shall get this done ASAP.
