### ISSUE TITLE
Existing components are affected

### ISSUE THREAD

**Issue by rishavkr08** [neetozone/neeto-editor#108]
- [ ] `h1` tag has extra margin
- [ ] Nested neetoUI Dropdown not working

Issue - [video](https://www.loom.com/share/ff3a87fa0ab84ec58c5907d4e425e3a1)

**Comment by rishavkr08** [comment]
@karthiknmenon _a

**Comment by amaldinesh7** [comment]
@goutham-subramanyam _a
