### ISSUE TITLE
Captions are still overlapping

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1082]
![Screenshot 2024-05-03 at 8 27 30 PM](https://github.com/bigbinary/neeto-editor/assets/9862943/b7f0e876-bc46-48e7-b6a9-7472db985924)

@gaagul _a please take it up on priority _t. It has been reported by a client _t who uses a lot of images in his documentation.

//cc @AbhayVAshokan

**Comment by gaagul** [comment]
@sandip-mane I had noticed this issue yesterday and added fix along with https://github.com/bigbinary/neeto-editor/pull/1080.

Upgrading the version of neeto-editor in neetoKb to the latest version will solve the issue. `v1.31.5` is the latest version.

**Comment by sandip-mane** [comment]
@gaagul could you please update the package in all the apps that use it?

**Comment by gaagul** [comment]
> @gaagul could you please update the package in all the apps that use it?

These changes will be rolled out on monday with compliance on all other apps, The changes are added to neetoKb: https://github.com/bigbinary/neeto-kb-web/pull/6145

**Comment by gaagul** [comment]
I will close the issue after testing in all the products after next compliance.

**Comment by gaagul** [comment]
Closing the issue since the latest editor version is released via compliance.
