### ISSUE TITLE
Ability to see a larger image

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1083]
After uploading the image in the editor, the images are shown in the editor.

- [ ] There should be a way to maximize the images to show in full-screen modal to see a larger preview

client _t

//cc @AbhayVAshokan @neerajsingh0101

**Comment by AbhayVAshokan** [comment]
@sandip-mane can you please provide a bit more clarity? A video would be good.

1. Where is the feature required? (Editor component (during edit) or EditorContent component (during preview)).
2. Is this the expected UI?
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/9ed5634f-8e30-4f69-a4b4-590b2f66aefe)

**Comment by sandip-mane** [comment]
@AbhayVAshokan https://sandip-mane.neetorecord.com/watch/45c3e00d-99c0-41d8-bfaf-efb31444e62f

**Comment by AbhayVAshokan** [comment]
Sounds good. @gaagul _a

**Comment by neerajsingh0101** [comment]
@sandip-mane captured the requirement beautifully.
