### ISSUE TITLE
Make triple dot consistent

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1084]
- [ ] Neeto's triple dot does not have a gray background.

![Screenshot 2024-05-03 at 8 49 05 PM](https://github.com/bigbinary/neeto-editor/assets/9862943/83b87bf8-1baa-4645-9e29-de4c84711bb6)

**Comment by sandip-mane** [comment]
@neerajsingh0101 if we remove the gray background here, the triple dots will look like a part of the image itself.

**Comment by AbhayVAshokan** [comment]
We can go with the `primary` button instead of `secondary` if it needs to stand out.

![image](https://github.com/bigbinary/neeto-editor/assets/35297280/1f4b3c77-80d4-412b-8b47-5f0b77f040ac)

**Comment by neerajsingh0101** [comment]
@sandip-mane @AbhayVAshokan https://neerajsingh0101.neetorecord.com/watch/c4b2cc7e-6140-44bd-ae99-e4f4221ca99a

**Comment by AbhayVAshokan** [comment]
@gaagul _a UI _t small _t
