### ISSUE TITLE
Change the Options pop-up position while selecting a row

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1088]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/6157

https://bigbinary.neetorecord.com/watch/4367ef21-8b5f-456e-bb18-5f60fa30036f

enhancement _t

**Comment by deepakjosp** [comment]
This will be fixed by https://github.com/bigbinary/neeto-editor/issues/1159
