### ISSUE TITLE
Option to add notes in editor

### ISSUE THREAD

**Issue by amaldinesh7** [neetozone/neeto-editor#109]
@amaldinesh7 _a

**Comment by karthiknmenon** [comment]
@jagannathBhat _a Please research on this.

**Comment by jagannathBhat** [comment]
@karthiknmenon Please take a look https://vimeo.com/695692608/8be1ea79a9

**Comment by AbhayVAshokan** [comment]
@karthiknmenon is this issue still relevant? As far as I understand, the notes feature is only used in neetoDesk. Since it is a single requirement, would it be better not to bring it to neetoEditor?

**Comment by karthiknmenon** [comment]
After some thought, this issue should be taken up in respective repositories. 
Also, kb would have notes. 
Closing this.
