### ISSUE TITLE
Feature request: calling setFieldValue should change the value of editor

### ISSUE THREAD

**Issue by subins2000** [neetozone/neeto-editor#1092]
@AbhayVAshokan _a https://subin-siby.neetorecord.com/watch/bca57cb4-776e-4f4d-8451-005e1427b04e

**Comment by AbhayVAshokan** [comment]
@subins2000 Tiptap editor is built as an uncontrolled component. This is why updating the state do not update the editor content itself. We have tried workarounds in the past to mimic controlled state within the editor. This introduced a lot of bugs and performance issues. Please use the `setContent` method as suggested in the video to update the content.

---

We shall take up the live examples as you suggested.
https://storybook.js.org/addons/storybook-addon-live-examples
