### ISSUE TITLE
Adding text/paragraph between images is very difficult

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1093]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/6166

---

Users wont be able to get the cursor between images due to the caption. 

https://alan-george-mathews.neetorecord.com/watch/4a32ee1f-2ca1-4b90-b037-4265da87b8cd

---

### Action items:
- [x] `Enter` in caption should add a new line after the image and add focus to the line
- [ ] Using backspace should not focus on the caption (Can be done with up/down arrow or mouse clicks)

**Comment by deepakjosp** [comment]
@AbhayVAshokan please check.

https://deepak-jose.neetorecord.com/admin/recordings/59f4e4a7-41a3-4bf7-af1c-7f34a4a6238b

**Comment by AbhayVAshokan** [comment]
@deepakjosp I agree. Pressing back space should take the user to the caption since it is the normal flow.
