### ISSUE TITLE
Backspace key isn't clearing content

### ISSUE THREAD

**Issue by abilash-sajeev** [neetozone/neeto-editor#1097]
The `backspace` key isn't deleting text in the Editor component as expected

**Comment by AbhayVAshokan** [comment]
@abilash-sajeev can you please post a video?

**Comment by abilash-sajeev** [comment]
@AbhayVAshokan 

https://github.com/bigbinary/neeto-editor/assets/35305344/20d15be5-999f-4391-88b9-b4cde27b8c77

**Comment by AbhayVAshokan** [comment]
@abilash-sajeev the issue can no longer be reproduced now. We have reverted the neetoEditor's beta version on Friday. Can you please verify if the issue is still reproducible and close the issue?

**Comment by abilash-sajeev** [comment]
This issue is not reproducible now.
