### ISSUE TITLE
Improve the UI of the editor fixed menu

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1105]
Part of https://github.com/bigbinary/neeto-editor/issues/1100

Before

### Type 1
<img width="1440" alt="Screenshot 2024-05-27 at 12 26 58 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/38952b1b-8bd3-445d-a469-eeff01230f86">

---

### Type 2
<img width="1440" alt="Screenshot 2024-05-27 at 12 28 47 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/905da31e-33e0-4bc1-9808-95c052b0b71b">
</br>
</br>
<img width="1440" alt="Screenshot 2024-05-27 at 12 28 57 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/a8c55286-adcf-47e6-8c24-0226a149bf4a">

Part of https://github.com/bigbinary/neeto-editor/issues/1100

@deepakjosp  _a

**Comment by deepakjosp** [comment]
@AbhayVAshokan  as we discussed @praveen-murali-ind will share a design approach to enhance the menu item's appearance and contrast and will implement the same.  I will update the ETA once the design is finalized. Currently moving on to auditing individual editor elements.

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _a Assigning myself to improve the look and feel of the menu.
