### ISSUE TITLE
Fix the UI issues in the upload modals in small screens.

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1121]
Part of #1100 
- [x] Image upload modal.
- [x] Video upload modal.
- [x] Video embed modal.

<img width="553" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/d6be35ab-865f-4f77-8171-185414dd51b3">

@praveen-murali-ind  _a

**Comment by praveen-murali-ind** [comment]
@thomas-mathai _a
