### ISSUE TITLE
Add a standardized email/pdf file CSS which ensures all items from neetoEditor are properly formatted

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#1140]
@deepakjosp _a Please refer: https://github.com/bigbinary/neeto-planner-web/pull/6192#pullrequestreview-2101512422

Working on adding the CSS logic just to neetoPlanner won't suffice. This issue affects all neeto products. We need a standardized CSS file.

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@yedhink can I know the priority of this issue? Deepak currently works on two issues that have a priority:
1. https://github.com/bigbinary/neeto-editor/issues/1123
2. https://github.com/bigbinary/neeto-editor/issues/1100

Both the issues are currently in progress.

**Comment by yedhink** [comment]
We can take this up after both of them are completed.

**Comment by yedhink** [comment]
@AbhayVAshokan How much more time do you think the other issues would take? Let me know if it would take more than a week from now. In that case we can think of assigning someone else on this issue since the dependent issue in planner is a request from a client.

**Comment by AbhayVAshokan** [comment]
@yedhink we shall pick this up this week once https://github.com/bigbinary/neeto-kb-web/issues/6392 is closed.
