### ISSUE TITLE
Improvise the UI of the upload progress modal.

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1156]
Part of https://github.com/bigbinary/neeto-editor/issues/1100

- UI/UX improvements for the upload modal.

@deepakjosp  _a

**Comment by deepakjosp** [comment]
@AbhayVAshokan @praveen-murali-ind this is what I'm planning as an improvisation to the current UI. Please let me know whether this is acceptable.

Proposal
<img width="501" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/be325128-06f4-40ee-b519-19d22b6ac738">

Current UI
<img width="652" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/89772922-7101-4a03-be61-8748377b4533">

**Comment by AbhayVAshokan** [comment]
@deepakjosp this looks great 👌

**Comment by praveen-murali-ind** [comment]
@deepakjosp This is looking great! ❤️  One minor suggestion, consider reducing the close button size and adding some padding around it (top and right).

<img width="116" alt="Screenshot 2024-07-11 at 10 39 37 AM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/40ef85eb-08c5-42d8-b92a-2e8f4995c09c">
