### ISSUE TITLE
 Convert neetoEditor to a controlled component

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1163]
Part of https://github.com/bigbinary/neeto-editor/issues/1100

- One of the main difficulties of using neetoEditor is that it can be only used as an uncontrolled component. This has a negative developer experience and needs the developers to directly use the editor API to mutate the content.
- The controlled version of neetoEditor should not impact the performance.

@deepakjosp  _a

**Comment by deepakjosp** [comment]
@AbhayVAshokan I was not able to work on this in this milestone because, I had to work for client couple of days in this milestone also. I have stretched the max to achieve the milestone, but this is beyond that and also requires extensive trials to make sure the changes doesn't impact the host apps. Could you please move this to next milestone?

**Comment by deepakjosp** [comment]
@AbhayVAshokan I couldn't find a feasible performant approach to make the editor controlled. I explored a few similar products built using TipTap and nobody uses it as a controlled component. In one of the repos they explicitly mentioned that it's not recommended to use the editor as a controlled component, since the editor content must be serialized to get the HTML string to render the data the user typed in. Considering this it's better to use the setContent function from the editor instance to set the content of the editor from outside.

**Comment by AbhayVAshokan** [comment]
Sounds good.
