### ISSUE TITLE
Unable to upgrade neeto-editor in Next.js app

### ISSUE THREAD

**Issue by sayoojtmc** [neetozone/neeto-editor#1170]
We were trying to upgrade neeto-editor in neeto-course-site to reduce bundle size, but got this error:

![image](https://github.com/bigbinary/neeto-editor/assets/32578593/8565ac6f-02d1-450c-9a0c-04a5e8c240ff)

Please check if this can be fixed.

**Comment by AbhayVAshokan** [comment]
@deepakjosp _a can you work with Sayooj on this issue? To reduce the bundle size, the imports needs to be updated to the `@bigbinary/neeto-editor/<component>` format.

**Comment by deepakjosp** [comment]
@sayoojtmc I was able to run the app in dev mode and create a production build after upgrading neetoEditor to the latest and refactoring the import. Please check and let me know if you face any issues.

<img width="976" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/2a90dd14-0513-4df8-9a9d-a8ecd2cf1454">
