### ISSUE TITLE
Icons for table menu.

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1181]
https://deepak-jose.neetorecord.com/recordings/be01e4ec-e172-4162-ba49-9bb2cb7507dc

Menu options:
-
1. Delete row
2. Delete column
3. Delete table
4. Insert row
5. Insert column
6. Merge/split,
7. Toggle header row

UI reference: https://www.richer-text.com/

https://monosnap.com/file/3cPkG00oYRYRz9jwb8kKi9cmGEtDdv

Part of https://github.com/bigbinary/neeto-editor/issues/1159

@avinashanilkumar could you please check?
cc: @praveen-murali-ind

**Comment by avinashanilkumar** [comment]
@deepakjosp _a Please find the icons

- [Delete row
](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-65&t=HCnPti21QCBl1r6r-4)
- [Delete column](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-64&t=HCnPti21QCBl1r6r-4)
- [Delete table](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-67&t=HCnPti21QCBl1r6r-4)
- [ Insert row](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-66&t=HCnPti21QCBl1r6r-4)
- [Insert column](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-63&t=HCnPti21QCBl1r6r-4)
- [Merge/split](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-68&t=HCnPti21QCBl1r6r-4)
- [Toggle header row](https://www.figma.com/design/t2CLe7RVJYwUq9E8Or1mQA/01-Fundamentals?node-id=6608-69&t=HCnPti21QCBl1r6r-4)

cc: @KirtiGulati

**Comment by deepakjosp** [comment]
@avinashanilkumar the new icons look cool.
<img width="721" alt="image" src="https://github.com/user-attachments/assets/b6d5d02d-3578-4805-88ae-b9dce6ca1810">


I've created a separate issue to add these to neeto-icons and integrate in the NeetoEditor. Closing the issue.
