### ISSUE TITLE
Writing feels sluggish

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#1204]
https://neerajsingh0101.neetorecord.com/watch/df8d3d22-24a8-494c-8901-e7ac713d8fcd

**Comment by AbhayVAshokan** [comment]
@deepakjosp has done a performance profile of NeetoKB in https://github.com/bigbinary/neeto-kb-web/issues/6610#issuecomment-2264722160 and identified a few problems.
1. https://github.com/bigbinary/neeto-hotkeys/pull/25: `neeto-hotkeys` introduced a lot of performance overhead in each keystroke. This PR fixes these issues.
2. https://github.com/bigbinary/neeto-kb-web/pull/6641: Refactor of NeetoKB codebase to prevent a performance impact.
3. https://github.com/bigbinary/neeto-editor/pull/1194: Prevent the rendering of heavy components when they are not in the viewport.
4. https://github.com/bigbinary/neeto-editor/pull/1173: Refactor and memoization of the menu component to reduce the performance impact.

In addition to this, there are several smaller optimizations done at several PRs. 

@deepakjosp _a I am assigning this issue to you. Please verify the NeetoKB performance once these changes reach production.

cc: @neerajsingh0101

**Comment by neerajsingh0101** [comment]
I wrote a bit more on that document and today also it was quite sluggish.

**Comment by deepakjosp** [comment]
The changes are in staging and I could see the sluggishness has gone. I've asked @sandip-mane to do a production deployment. Once the changes are in production, I'll verify and update here.

**Comment by sandip-mane** [comment]
@deepakjosp I have deployed the changes now, could you please verify?

//cc @neerajsingh0101

**Comment by neerajsingh0101** [comment]
I'll report back if I experience any issue when next time I write something.

**Comment by deepakjosp** [comment]
I have verified in production and the lag has gone. I tried verifying by typing a list of items and adding 10+ items. The key presses responded instantly. To compare, I was not able to type more than 2 items in the list when I tested before the release.

https://deepak-jose.neetorecord.com/admin/recordings/764df13b-8cef-4715-9cc8-c95131340f4e

**Comment by neerajsingh0101** [comment]
@deepakjosp The video looks fantastic. 😍
