### ISSUE TITLE
Fix the loading issue of documentation 

### ISSUE THREAD

**Issue by shreyakurian02** [neetozone/neeto-editor#1207]
The [neeto-editor](https://neeto-editor.neeto.com/?path=/story/sandbox--editor-sandbox&hash=cab706c76ec98b0399945a72b514a5070db5ae03) documentation isn’t loading.

@AbhayVAshokan _a

**Comment by deepakjosp** [comment]
I created a new storybook build from the main branch and it was working fine. The problem should be a build issue. No code changes are required. Let's re-visit if the issue persist.

cc: @AbhayVAshokan
