### ISSUE TITLE
Stroybook stuck on loading forever

### ISSUE THREAD

**Issue by sritabh** [neetozone/neeto-editor#1210]
Storybook is not accessible and showing spinner
>Snapshot of https://neeto-editor.neeto.com/?path=/docs/welcome--docs
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/af709716-2f3c-4584-b05c-93cb733a7386">

**Comment by deepakjosp** [comment]
@unnitallman the root of the error seems to be from the script to add "Powered by NeetoDeploy" banner. Could you please check?

`document.addEventListener('DOMContentLoaded',function(){var e=document.createElement('div');e.style.position='fixed';e.style.right='10px';e.style.bottom='10px';e.style.padding='10px';e.style.backgroundColor='#007BFF';e.style.color='#ffffff';e.style.borderRadius='5px';e.style.zIndex='9999';e.textContent='Powered by neetoDeploy';document.body.appendChild(e)});`

<img width="705" alt="image" src="https://github.com/user-attachments/assets/4c5213db-9580-4eac-a87e-0b33cff34548">

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@vishal24367 _a: It seems like the script is defined in [neeto-deploy-dyno-manager/badge-middleware](https://github.com/bigbinary/neeto-deploy-dyno-manager/blob/7f00cfcede39b7eb4f3fe7ca1b58e97fd2a0f571/app/k8_files/badge-middleware.yml#L11-L13). Can you please check if the script is defined correctly?

**Comment by vishal24367** [comment]
@abhishekt98 _a

**Comment by abhishekt98** [comment]
This has been fixed.
