### ISSUE TITLE
Add a `isVariableSubstitutedAsLabels` prop

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#1217]
Ref: https://github.com/bigbinary/neeto-form-web/issues/8982

https://abhay-ashokan.neetorecord.com/watch/875c5140-ba76-4172-8fec-19ce971b1506

---

- [x] Add a `isVariableSubstitutedAsLabels` prop (false by default). If this variable is enabled, the variables should be rendered using labels instead of ids. This can be implemented by writing a NodeView to render the Editor content.
- [x] In case of longer labels/questions, we can truncate it to 15 characters and then suffix it with ...

@deepakjosp _a

enhancement _t

**Comment by deepakjosp** [comment]
@AbhayVAshokan I had a call with @subins2000 and they are okay with showing the variable's label in NeetoCal. Hence I'm not adding a variable to control whether the Editor should display a label or id for the variables.
