### ISSUE TITLE
Issues in rendering dynamic variables in NeetoEditor

### ISSUE THREAD

**Issue by abilash-sajeev** [neetozone/neeto-editor#1240]
https://abilash-sajeev.neetorecord.com/watch/d56a1d44-2fe4-425a-b87c-e4f3b2e9a962

**Comment by abilash-sajeev** [comment]
@AbhayVAshokan Can we prioritize this issue?  It would be great if this could be fixed in the current milestone.

**Comment by AbhayVAshokan** [comment]
@abilash-sajeev: We already have https://github.com/bigbinary/neeto-form-web/issues/11661 to track the first part of the issue. It will be done in the current milestone.

@deepakjosp _a: Let's look at the second part of the issue here - multiple variables with the same names.

**Comment by AbhayVAshokan** [comment]
I am removing the priority label since the important sub-issue is already taken up in M21.
