### ISSUE TITLE
Make tables responsive

### ISSUE THREAD

**Issue by praveen-murali-ind** [neetozone/neeto-editor#1258]
@praveen-murali-ind _a

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan https://praveen-murali.neetorecord.com/watch/4899684d-b7e7-4401-9068-2c334a05dfad

## After

<img width="1440" alt="Screenshot 2024-11-05 at 9 19 46 PM" src="https://github.com/user-attachments/assets/8e8e34d3-85e3-4d24-886f-761adcc394db">

<img width="1440" alt="Screenshot 2024-11-05 at 9 19 22 PM" src="https://github.com/user-attachments/assets/53d550bc-3ebc-48f3-9294-6793b628f07b">

cc @neerajsingh0101

**Comment by neerajsingh0101** [comment]
@praveen-murali-ind looks great 👍
