### ISSUE TITLE
Add placeholder on selecting slash menu items, video embed UI improvement

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#126]
- [ ] Add placeholders when slash menu items are selected.
Ref: ![Slash commands focus](https://user-images.githubusercontent.com/35297280/147815238-d54e733c-3c1b-4663-9b95-b549d0092300.png)
- [ ] Add an inline input field to convert entered links to embeds.
Ref: ![Video embed](https://user-images.githubusercontent.com/35297280/147815296-74c20b4f-87b8-470f-95ca-7f2eb5962a2d.png)

enhancement _t
@AbhayVAshokan _a

**Comment by karthiknmenon** [comment]
@karthiknmenon _a
