### ISSUE TITLE
UI Enhancements required after removing CSS overrides from NeetoKB

### ISSUE THREAD

**Issue by philson-philip** [neetozone/neeto-editor#1260]
Ref - https://github.com/bigbinary/neeto-kb-web/issues/7138

**Comment by philson-philip** [comment]
### 1. Improve letter spacing for Heading tags

### Before
![Screenshot 2024-11-06 at 5 26 29 PM](https://github.com/user-attachments/assets/415cec9a-942a-4cb4-9707-48262bcd9cfa)

### After
![Screenshot 2024-11-06 at 5 25 57 PM](https://github.com/user-attachments/assets/38fc75f6-c439-463e-a5d1-d02234baab3c)

**Comment by philson-philip** [comment]
### Heading and Content

- [x] Heading tag - Line height changes, Font size changes for h4 - h6
- [x] Paragraph tag - Line height changes
- [x] Strong/bold tag - Font weight changes from 700 to 600
- [x] Link - Font weight changes from 400 to 500
- [x] ol -> li tag - Margin changes - (Added top margin)
- [x] Code - Font size changes from 14px to 16px
- [x] Table heading - Font weight changes from 700 to 400, Background color change
- [x] Image, Video, Embed video - Border is missing
-----
### Editor Output - Code block content
#### Before
![Screenshot 2024-11-07 at 12 05 30 PM](https://github.com/user-attachments/assets/c458ed36-911f-40d7-9470-0f3d5c5c345a)
#### After
![Screenshot 2024-11-07 at 12 05 20 PM](https://github.com/user-attachments/assets/f89b9fee-749a-4e31-a82e-be81a739cfd9)
-----
Ref - 
Old style - https://philson.neetokb.com/articles/lorem-ipsum
New style - https://philson.neetokb.net/articles/lorem-ipsum

cc: @praveen-murali-ind

**Comment by praveen-murali-ind** [comment]
@philson-philip I have fine-tuned the editor elements in [this pull request](https://github.com/bigbinary/neeto-editor/pull/1265). These changes are intentional, and I have verified them locally on KB and Planner.
