### ISSUE TITLE
Add an attachment prop to permit file uploads

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#128]
- Add a prop to allow attachments to the editor. Refer the quoted comment:
> As far as attaching files is concerned, yes, let's have an attach icon that allows folks to attach files. The attached files will not be embedded into the editor rather will be added as neetoUI Tags above the editor area.
> Ref -
> ![](https://user-images.githubusercontent.com/41678651/147468981-deee0179-2738-4b99-910a-48344bbe9e61.png)

Ref: https://github.com/bigbinary/neeto-desk-web/issues/11327#issuecomment-1001529408

enhancement _t discussion _t

**Comment by vysakh-poulose** [comment]
There is a requirement for attachments to permit file uploads in neetoDesk. Please make it a high-priority task.
Ref: https://github.com/bigbinary/neeto-desk-web/issues/12030
cc @amaldinesh7

**Comment by sandip-mane** [comment]
We do not need attachments support with the editor itself. 
We need just a way to add an attachment icon in the editor's toolbar. The editor itself does not need to support the file uploads etc. it can be handled in the client apps separately.

You can close this issue if it makes sense.


//cc @karthiknmenon
