### ISSUE TITLE
[neeto-kb-frontend/production] TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1281]
https://github.com/bigbinary/neeto-kb-web/issues/7230

**Comment by labeebklatif** [comment]
Looks like latest codebase already has additional conditions in place to prevent this error from raising. Closing the issue.
https://github.com/bigbinary/neeto-editor/blob/main/src/components/Editor/CustomExtensions/CodeBlock/plugins.js#L15
