### ISSUE TITLE
[neeto-kb-frontend/production] TypeError: Cannot read properties of undefined (reading 'children')

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#1282]
https://github.com/bigbinary/neeto-kb-web/issues/7231

**Comment by AbhayVAshokan** [comment]
@deepakjosp _a

**Comment by labeebklatif** [comment]
Closing the issue as the issue was not reproduced and insufficient information available for tracking the source. There is only 1 reported occurrence. This can be taken up if issue is more persistent and more information is available.
