### ISSUE TITLE
Create a JS script to support image preview feature in pages that uses vanilla JavaScript.

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#1287]
We only support the image preview feature in the EditorContent which is a react component. The blogs NeetoWebsite blogs cannot preview the images and the NeetoPublish and NeetoKb use a custom implementation. Let's move that to the NeetoEditor and serve as a script via CDN so that the implementation remains consistent.

ToDo
--
- [ ] Port the image preview script to NeetoEditor and serve it via CDN from NeetoEditor.
- [ ] Replace the custom usages in NeetoKB, NeetoPublish and other similar products with the script served by NeetoEditor.

@AbhayVAshokan _a could you please assign this to someone to work on?
cc: @praveen-murali-ind

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a

**Comment by deepakjosp** [comment]
@AbhayVAshokan this issue is duplicate of https://github.com/bigbinary/neeto-editor/issues/1277.
