### ISSUE TITLE
Editor content in view mode issue

### ISSUE THREAD

**Issue by rishavkr08** [neetozone/neeto-editor#131]
@amaldinesh7 _a https://youtu.be/gFIk6Cv2aVE

**Comment by amaldinesh7** [comment]
@rishavkr08 _a Please check the Output section in the documentation - https://neeto-editor.netlify.app/.

**Comment by rishavkr08** [comment]
@amaldinesh7 I already checked the editor, in the console it prints correctly. But in the application, the view is different.

**Comment by rishavkr08** [comment]
Works fine with EditorContent component of neeto-editor.
