### ISSUE TITLE
Variable support popover buttons are not uniform.

### ISSUE THREAD

**Issue by AkhilXavier95** [neetozone/neeto-editor#147]
On the variable support popover when the variable list for a category has a few options, the button does not look uniform.
  
![image](https://user-images.githubusercontent.com/45327726/149953855-c59b506a-01aa-45da-876c-e69a204f5720.png)

When i added "flex-wrap: wrap" it looks like:
![image](https://user-images.githubusercontent.com/45327726/149954137-509ee59a-8425-4ed8-aa93-0e3538a60959.png)

**Comment by karthiknmenon** [comment]
@goutham-subramanyam _a Please look into this.
