### ISSUE TITLE
What is the purpose of allowing `mentions` prop to take in different datatypes?

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#149]
https://www.loom.com/share/f735b87a267f496da66103a8ed7e65b5

@AbhayVAshokan  _a

Can you take a look into this? Please close this issue if this doesn't seem feasible.

cc: @amaldinesh7

**Comment by AbhayVAshokan** [comment]
@yedhink yes, it is possible to refactor the same to an array of objects. It does reduce a lot of unnecessary confusion.

I am thinking of refactoring the same just like the `Avatar` component in neetoUI:
```ts
Array<{name: string, imageUrl: string}>
```
I shall look into the feasibility of removing the `key` prop and using a slugified version of the `name` for the same.

cc: @amaldinesh7 WDYT?

**Comment by labeebklatif** [comment]
@AbhayVAshokan regarding using the `name` property for generating `key`: the `key` is actually intended to be a unique data attribute in the mention tag for the backend to identify the user that was mentioned. There could be multiple persons having same name in which case we may have to pass something unique as user id to as the key property but the user's name has to be shown in the interface for the users to choose. So, I feel like the `key` if explicitly specified, we need to use it directly. In case `key` is not specified, you may use the slugified `name` for `key` as you see fit.
