### ISSUE TITLE
Range Error when pasting text containing @NonExistingUser into an empty editor

### ISSUE THREAD

**Issue by muhsinfazal** [neetozone/neeto-editor#163]
Text Pasted: Hello @NonExistantUser

Error while trying to paste the above text into an empty editor

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48003306/153347022-3d12e5e0-2ead-4efb-8404-85bcf7083d22.png">

On the other hand, it's working fine if we replace the default existing text with the same text we pasted above.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48003306/153347212-6978aa8c-cb93-4f2d-985b-f4db769369ff.png">

**Comment by amaldinesh7** [comment]
@AbhayVAshokan _a

**Comment by karthiknmenon** [comment]
@jagannathBhat _a

**Comment by jagannathBhat** [comment]
@karthiknmenon This is a bug in the `tiptap` package. Similar bugs were reported in the package repo. (Example: https://github.com/ueberdosis/tiptap/issues/2246)

CC: @amaldinesh7

**Comment by AbhayVAshokan** [comment]
@AbhayVAshokan _a
