### ISSUE TITLE
Quick look into shortcuts of tiptap

### ISSUE THREAD

**Issue by karthiknmenon** [neetozone/neeto-editor#165]
@vysaghsekharbb _a 

TipTap has a variety of [shortcuts](https://tiptap.dev/api/keyboard-shortcuts). We need to be bale to provide a customer with a quick glance of all related shortcuts and other hotkeys like `enter` `shift + enter` and so on. 

UX _t 

cc: @labeebklatif @amaldinesh7 @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
Adding a low-priority _t label for this issue. 

@vysaghsekharbb please provide an update on this issue when you're free.

**Comment by AbhayVAshokan** [comment]
@vysaghsekharbb can we replicate the implementation in neetoChat here? Looks pleasing.
![rq](https://user-images.githubusercontent.com/35297280/168757450-0e80406b-8c27-4514-82ba-bcb5d972aa64.gif)

**Comment by AbhayVAshokan** [comment]
Closing this issue. All the existing shortcuts are basic text editing and markdown shortcuts.
cc: @karthiknmenon
