### ISSUE TITLE
Allow applying styles on all children of neeto-editor-content

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#166]
https://www.loom.com/share/0e2c783b3ee54c4fb915306ce9facb9d

@AbhayVAshokan _a

Please take a look into this.

Issue origination: https://github.com/bigbinary/neeto-engage-web/pull/280#issuecomment-1038735622

cc: @labeebklatif

**Comment by labeebklatif** [comment]
@yedhink Went through the issue that you mentioned. I have a feeling that passing the same className to each nodes inside the editor content may not be a viable approach. there could be certain nodes which doesn't want that particular styles applied. passing the same class for every nodes takes away this control. the intended use of the className prop is to allow users to add their own custom class to the outer container. the nodes inside can be targeted and styled separately using css like how you have mentioned as possible fix in the video. if we apply the same container class to container and each and every node inside, this will make it difficult to target nodes. 

as an alternative, we may take separate prop, may be something like `contentClassName` and apply this to every node if wanted. but I think this is against the convention that we follow.

let me know what you think.

cc: @karthiknmenon, @AbhayVAshokan

**Comment by yedhink** [comment]
>as an alternative, we may take separate prop, may be something like contentClassName and apply this to every note if wanted.

I would suggest adding this.

>but I think this is against the convention that we follow.

@labeebklatif Can you please elaborate more on this? Thanks.

**Comment by labeebklatif** [comment]
> @labeebklatif Can you please elaborate more on this? Thanks.

@yedhink  Correct me if I'm wrong but I think I have read somewhere in our guide/convention that we don't take each and every style inside a reusable component as props and instead we take a single className prop for the component container and use css for overriding the element styles further down the tree. But now, I couldn't find the reference for this.

let me know If I can go forward with adding the `contentClassName` prop.

**Comment by yedhink** [comment]
@karthiknmenon You can make the final call on this.

I would stick on to my previous suggestion that is to add this prop, because we'd be fixing an actual issue and moreoever keeping things sane.

The component here is named `EditorContent`. Which means we are dealing with `content` right? If I apply className to it, then it gets only applied to container as mentioned by Labeeb. As an end user, who uses other neetoUI components, not sure this pattern aligns with the convention of using `className` prop to apply styles to the component. Example take the [Button component from neetoUI](https://github.com/bigbinary/neeto-ui/blob/6db1d4f41085065b8eed87985234892284cd0238/lib/components/Button.js#L75) and how it's using `className`.

Here the prop should have been named `containerClassName` over `classNames` and we should add another className called `contentClassName`.

PS: I still haven't understood [why it's named plural `classNames`](https://github.com/bigbinary/neeto-editor-tiptap/blob/bbf6763ab05f8e1f4b6a970193acd89282392430/lib/components/Editor/EditorContent.js#L16) over singular `className` in this component.

**Comment by labeebklatif** [comment]
> PS: I still haven't understood [why it's named plural `classNames`](https://github.com/bigbinary/neeto-editor-tiptap/blob/bbf6763ab05f8e1f4b6a970193acd89282392430/lib/components/Editor/EditorContent.js#L16) over singular `className` in this component.

This prop `classNames` must have been named so by mistake, or typo. will be changing that.

**Comment by karthiknmenon** [comment]
@labeebklatif @yedhink Please watch the following [loom video](https://www.loom.com/share/1f9deb20cd7a495eb7d96eba495247c5) for more details. Lmk your thoughts on this. 

cc: @AbhayVAshokan @amaldinesh7 @goutham-subramanyam

**Comment by labeebklatif** [comment]
Will rename the prop `classNames` to `className` and this can be used to target elements down the tree. I think no other changes required.

**Comment by AbhayVAshokan** [comment]
I agree with this argument. Adding an `contentClassName` prop for all the children may provide unintended behavior for the different types of nodes. Here is a reference from KB where we add individual styles to different nodes: [_article.scss](https://github.com/bigbinary/neeto-kb-web/blob/master/app/javascript/stylesheets/pages/_article.scss#L28-#L94).

**Comment by karthiknmenon** [comment]
@labeebklatif _a Assigning this to you. Please make the necessary changes with prop renaming. Please document the changes as well.

**Comment by AbhayVAshokan** [comment]
Closed #166 via #192.
