### ISSUE TITLE
Auto submitting  formik form on clicking on emoji.

### ISSUE THREAD

**Issue by ajil-paul** [neetozone/neeto-editor#170]
- Add neetoEditor inside a Formik wrapper.
- Add emoji add-on in neetoEditor.
- The form will get submitted just by clicking on emoji in neetoEditor.

	https://vimeo.com/679147793/a56099e3a0

@AbhayVAshokan _a Please look on this issue

**Comment by AbhayVAshokan** [comment]
> Add neetoEditor inside a Formik wrapper.

@AJIL-PAUL can you please explain this point?

- Adding a `formik` wrapper would need to install it as a peer- dependency.
- Isn't it feasible to set `setFieldValue` in the onChange function? The same is applicable to components like ColorPicker in neetoUI.
