### ISSUE TITLE
Thoughts on horizontal ...

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#185]
https://www.loom.com/share/4445641281a44907b54ce413f19f7448

**Comment by neerajsingh0101** [comment]
Here is another example of vertical dots. https://monosnap.com/file/3gDCHe9yM7dfO78tLIqAcjc9pk6jVm

**Comment by AbhayVAshokan** [comment]
@karthiknmenon I believe the choice of `MenuHorizontal` comes from the product level in neetoUI Table. If so, where would be the best place to raise this issue? Also, can you please share your thoughts on the same?
