### ISSUE TITLE
Update the style for links

### ISSUE THREAD

**Issue by MelvinMathew9** [neetozone/neeto-editor#201]
Ref - https://github.com/bigbinary/neeto-planner-web/issues/956
Video - https://www.loom.com/share/d7979b686c5842b6833383d21bf8496e?t=80

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
Closing this issue. Update `neetoEditor` to the latest version to add styles to links in `EditorContent`. Default styles can be overridden on the product level using the `neeto-editor-content` class.

Ref: [neetoKb#_article.scss](https://github.com/bigbinary/neeto-kb-web/blob/634bdb4a8f07d1f1c73ecc71d5b0a2b0e22e0ed8/app/javascript/stylesheets/pages/_article.scss#L28-L94)
