### ISSUE TITLE
When uploading images with unsupported extensions, a suitable validation message should appear

### ISSUE THREAD

**Issue by abhirampai** [neetozone/neeto-editor#212]
Refer: https://github.com/bigbinary/neeto-runner-web/issues/1380

**Comment by nithinkr1shna** [comment]
@labeebklatif Is it possible to show a message or something when we upload a file that is not supported by the editor?

cc: @AbhayVAshokan, @abhirampai

**Comment by AbhayVAshokan** [comment]
<img width="834" alt="Screenshot 2022-04-05 at 4 35 10 PM" src="https://user-images.githubusercontent.com/35297280/161740630-cc80114c-b6c8-471d-bbf2-fe169d975b9f.png">

@nithinkr1shna, as far as I know, all the file formats that are not images are greyed out (refer to image). So it is impossible to select them and show validations.

**Comment by nithinkr1shna** [comment]
@AbhayVAshokan: Users can click on options and select `All files`. 

Mac: 
<img width="1440" alt="Screenshot 2022-04-05 at 5 50 58 PM" src="https://user-images.githubusercontent.com/22771826/161752570-dcfc57a4-6a92-489b-9df8-201276700f36.png">

Windows:
![image](https://user-images.githubusercontent.com/22771826/161753216-d2609a5e-4b2e-4921-bf69-ef55120d2b4d.png)

Share your thoughts!

**Comment by AbhayVAshokan** [comment]
Yes, will work on it.
