### ISSUE TITLE
Discrepancy between the default value and empty value of the editor

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#231]
Context: https://github.com/bigbinary/neeto-cal-web/pull/297#issuecomment-1127573140

@AbhayVAshokan _a Can you please point out why exactly is the default value of the editor an empty string and the empty value is updated to `p` tag when a manual change has been made to the editor? 

It seems like a discrepancy to me. Can we keep the default value as `p` tag itself rather than empty string?

**Comment by yedhink** [comment]
I think in neetoCal we set the initial value as an empty string and that's what caused this issue in the first place. Refer: https://github.com/bigbinary/neeto-cal-web/pull/297/commits/2c59cc06ec95bed9158fe320dd5fd4c7703e60da#diff-ebc43a2c2ab5c7616f74a62b650f47d70b01c655c50ef3c35cadbaf632b1a0c6L49

But can we add a warning to point out that neetoEditor expects empty value as `<p></p>` rather than empty string?

**Comment by AbhayVAshokan** [comment]
@yedhink the editor accepts any valid HTML content as the initialValue. The editor recognizes both empty string and `<p></p>` tags as the empty states for the editor.

A [similar issue](https://github.com/ueberdosis/tiptap/issues/154) was raised in Tiptap and was closed without a proper explanation for it. After exploring a few WYSIWYG editors, I understood that all these editors have `<p></p>` tag when the editor content is empty. It is possible to explicitly remove the paragraph tags if there is no other content in the editor. But doing so will raise inconsistencies between the editor content in other methods.

> But can we add a warning to point out that neetoEditor expects empty value as `<p></p>` rather than empty string?

Yes, this does seem like the right way to move forward to prevent similar issues.

**Comment by AbhayVAshokan** [comment]
@mohit-s96 _a please take this up.

**Comment by subins2000** [comment]
> I understood that all these editors have <p></p> tag when the editor content is empty.

@AbhayVAshokan Would it be possible that neetoEditor frontend expose a function to check whether a given neetoEditor value is empty or not i.e if the value is `<p></p>`, return true. We don't need to rewrite this function everywhere.

**Comment by AbhayVAshokan** [comment]
@subins2000 use the `isEditorEmpty` method. Import it from `@bigbinary/neeto-editor`.
