### ISSUE TITLE
Some emojis are not rendered properly

### ISSUE THREAD

**Issue by ajmaln** [neetozone/neeto-editor#247]
Refer: https://github.com/bigbinary/neeto-form-web/issues/2771

Stackoverflow: https://stackoverflow.com/questions/51902495/chrome-is-not-displaying-my-emoji-correctly

@AbhayVAshokan  _a

**Comment by AbhayVAshokan** [comment]
Taking this up after #246 is resolved since it makes a lot of changes related to emojis.
