### ISSUE TITLE
Copy pasting direct images to editor should not be allowed

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#264]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/1520

**Comment by AbhayVAshokan** [comment]
If I understood it correctly, when an unsupported image is pasted, the image icon should not be displayed. Perhaps an error for the same can be provided. Is this what is expected @sandip-mane?

**Comment by sandip-mane** [comment]
@AbhayVAshokan it's not about the unsupported image.

When the user actually copy-paste's **image contents** then it should work as it works right now but,
when the user copy-paste's actual files i.e. `.jpeg`, `.png` etc, we show a file preview icon instead of the file. This should not happen, IMO this thing should not get pasted and no need to show any errors.

**Comment by sandip-mane** [comment]
This issue is not relevant anymore. Seems like it has been fixed earlier.
