### ISSUE TITLE
Change bundler to Rollup

### ISSUE THREAD

**Issue by amaldinesh7** [neetozone/neeto-editor#266]
@amaldinesh7 _a

**Comment by AbhayVAshokan** [comment]
@amaldinesh7 what is the update on this PR? There is a slight issue with the current Webpack. After Webpack was updated to `v5.64.3` (while adding the storybook), it raises the error `ReferenceError: react is not defined`. 

If this is ready we can proceed to replace Webpack with Rollup and this issue can be solved.

Ref:
<img width="1416" alt="Screenshot 2022-07-04 at 6 58 46 PM" src="https://user-images.githubusercontent.com/35297280/177164748-32ad04e5-2fca-4b16-b702-8cf936186a21.png">
