### ISSUE TITLE
Advanced link features

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#276]
In neetoKB, we have a requirement where all the links should open in new tab. i.e. `target=_blank`.

This can be made configurable with a prop: `targetForLinks="_blank"`.

![image](https://user-images.githubusercontent.com/9862943/178765928-e21a4dc5-6b90-4baf-9d4d-41c6049f42f7.png)

**Comment by AbhayVAshokan** [comment]
@sandip-mane the links in the "preview" open in a new tab by default. Are you suggesting whether the links in the editor should open in a new tab as well? Currently, clicking the link just triggers the bubble menu.

**Comment by sandip-mane** [comment]
@AbhayVAshokan my bad, it is opening the links in new tabs. Thank you!

Closing the issue.
