### ISSUE TITLE
Enhancements related to how we handle images

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#277]
https://www.loom.com/share/86731833b7a54951a1fad6214034f3e0

Can we take this up on a higher priority given that it has to do with neetoQuiz?

**Comment by AbhayVAshokan** [comment]
- [x] #280 
- [x] #281 
- [x] #288
- [x] #264
- [x] #283
- [x] #295
- [x] neetoQuiz: Use `@bigbinary/neeto-editor` package instead of directly installing from git.

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@karthiknmenon can you please share your thoughts on how the delete feature must be implemented? As of now, an image can be deleted only by pressing the delete button.

**Comment by karthiknmenon** [comment]
@AbhayVAshokan 
Let's do it like notion, for images, we can have a custom floating menu that also has an option to delete.
