### ISSUE TITLE
Text color bug

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#279]
Refer: https://github.com/bigbinary/neeto-kb-web/issues/1851

**Comment by AbhayVAshokan** [comment]
- All formatting can be avoided by using `Cmd + Shift + V` instead of `Cmd + V` while pasting content.
- As of now, there is no mechanism to update text color when the menu type is `bubble`.

@karthiknmenon please share your thoughts on adding the text color option to the bubble menu.

**Comment by sandip-mane** [comment]
@AbhayVAshokan I don't think we need more formatting options, I think we can add `Paste Unformatted` option in the slash commands menu and we should be good.
