### ISSUE TITLE
Image Upload Process

### ISSUE THREAD

**Issue by karthiknmenon** [neetozone/neeto-editor#29]
@labeebklatif Please work on the following changes - 

- [x] #31
- [x] #34
- [x] #120 

Since this is an epic issue, please break the issue down into 3 individual issues and raise PRs corresponding to each of it. 

cc: @edwinbbu

**Comment by labeebklatif** [comment]
Noted

**Comment by karthiknmenon** [comment]
@AbhayVAshokan _a Could you research into Unsplash integration? 

cc: @labeebklatif, @amaldinesh7

**Comment by AbhayVAshokan** [comment]
Closing this `epic` issue since all three tasks are complete.
