### ISSUE TITLE
Content issue with markdown type

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#290]
1. Create an article that has multiple lines (prose-style)
2. Save the article to see the content in one single line

**Before:**
![Screenshot 2022-07-21 at 10 18 36 AM](https://user-images.githubusercontent.com/9862943/180132192-765c0fc2-b8d9-4317-9e50-0bab66328782.png)

**After:**
![Screenshot 2022-07-21 at 10 18 43 AM](https://user-images.githubusercontent.com/9862943/180132198-330a476e-3e83-4992-a4c4-25e1e0c449dc.png)

**Comment by AbhayVAshokan** [comment]
@sandip-mane we have removed markdown mode from neetoEditor.
Ref: https://github.com/bigbinary/neeto-editor-tiptap/pull/274

- The rich text mode automatically converts almost all the markdown syntax. 
- Preview of the markdown mode is not available.
- Markdown mode introduces a lot of bugs.

@karthiknmenon I understand that markdown mode will be completely removed from neetoKB. If needed, it can be implemented in an alternate way.

**Comment by sandip-mane** [comment]
@AbhayVAshokan do we have to remove this mode from neetoKB or handle markdown in neetoKB itself?

//cc @karthiknmenon

**Comment by karthiknmenon** [comment]
@sandip-mane @AbhayVAshokan I will comment back on this by EOD today. Need sometime to ideate the process.

**Comment by AbhayVAshokan** [comment]
Closing this issue. Markdown mode is removed neetoKB, and hence not used in any Neeto repo.
