### ISSUE TITLE
Automatic List indentation doesn't exit even after providing keystrokes to exit from it

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#297]
https://www.loom.com/share/105b71585b334f78a26a04e9c6269d4a

@AbhayVAshokan _a We should keep it aligned with how Slack does it. Not sure if this issue is specific to neetoPlanner. If yes, then please transfer this issue to that repo.

cc: @sandip-mane @Melvin9

**Comment by AbhayVAshokan** [comment]
@yedhink https://vimeo.com/733264163/f0fdd68ea9

**Comment by yedhink** [comment]
@AbhayVAshokan Pressing `enter` two times to exit the list indentation is also fine. We can go ahead with that logic. If that logic already exists, then please close this issue.
