### ISSUE TITLE
Add support for emojis

### ISSUE THREAD

**Issue by karthiknmenon** [neetozone/neeto-editor#30]
@labeebklatif _a Please check the issue. I have attached a few screenshots for reference. 

Ref - 
![image](https://user-images.githubusercontent.com/41678651/141839701-2f05a5f0-46d7-4eb6-b22f-78b7891fc7c2.png)
![image](https://user-images.githubusercontent.com/41678651/141839725-4760d771-4a92-48ca-9f3f-0e87dc42ad27.png)

cc: @edwinbbu

**Comment by amaldinesh7** [comment]
@AbhayVAshokan _a
