### ISSUE TITLE
Default keybindings for submission and newline

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#301]
https://www.loom.com/share/0ad5931256724fafb003bedee7a2ab8b

@AbhayVAshokan _a Please take this up.

Reference: https://github.com/bigbinary/neeto-planner-web/issues/1920

**Comment by AbhayVAshokan** [comment]
@yedhink please have a look at this video and try out the same here: https://neeto-editor.onrender.com/?path=/story/examples-basic--basic
https://vimeo.com/733602773/40decd0658

PS: Apart from what is mentioned, `Cmd + Enter` and `Ctrl + Enter` will trigger the `onSubmit` callback. Any number of new keybindings can be added to override or add new behaviours.

**Comment by yedhink** [comment]
@AbhayVAshokan Does entering a block behave the same way as a newline? Meaning `Shift+Enter` and `Enter` seems to do two different things.

My question boils down to whether `Enter` will trigger `onSubmit` whereas `Shift+Enter` wouldn't.

**Comment by AbhayVAshokan** [comment]
- By default, `Enter` or `Shift+Enter` does not triggger `onSubmit` callback.
1. `Enter`: Creates a new paragraph tag. There is a visible margin between two paragraphs.
2. `Shift + Enter`: Inserts a `<br/>` tag within the paragraph.

The idea is to make it easy to create new blocks while writing a large article in neetoKB.

**Comment by yedhink** [comment]
Got it. Then I think we are on the clear on neetoEditor side. Thanks for clarifying the queries. Closing this issue.
