### ISSUE TITLE
Enhance Ordered list

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#307]
https://www.loom.com/share/7aa8e7d92f514063855902010a3d9f4c

@AbhayVAshokan _a This is a bug i think.

**Comment by AbhayVAshokan** [comment]
@yedhink please have a look: https://vimeo.com/735320951/4c154b290c

**Comment by yedhink** [comment]
@AbhayVAshokan _a Makes sense. Let's update the margin.

But more than that, just like in Notion, it would be great if we can highlight the block that will be converted to an ordered list when we hover on the `ordered list` icon from the formatting bar. That will give the visual idea about what we are doing.

Lemme know your thoughts.

**Comment by AbhayVAshokan** [comment]
I agree, this should remove any confusion regarding this. Taking this up.
