### ISSUE TITLE
Insert nodes created from FixedMenu at the end

### ISSUE THREAD

**Issue by abrahamparayil** [neetozone/neeto-editor#310]
Elements from the fixed menu are inserted at the beginning of the content at the moment. This can be cumbersome for the user when there is already some content in the editor. Ideally, such elements should be inserted at the end.

https://vimeo.com/737784830/c7a0074df8

@AbhayVAshokan _a Please take a look.

**Comment by AbhayVAshokan** [comment]
@labeebklatif _a can you please share your thoughts on this issue?

https://vimeo.com/738148799/92fcb6bd92

cc: @abrahamparayil 
low-priority _t

**Comment by labeebklatif** [comment]
IMO, let's keep this as Low priority as discussed for now. Will look into this once I have some bandwidth.
