### ISSUE TITLE
:thumb should show thumbsup before showing thunder

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#317]
https://www.loom.com/share/5a988966a350460ca74ed9b0c1deff76

**Comment by AbhayVAshokan** [comment]
@neerajdotname the `emoji-mart` package does not provide control over how the results must be sorted. 

Would it be better if the default emojis are changed to more useful ones? By "default emojis", I mean the emojis that show up as soon as a "colon" is typed.

Eg: default emojis of GitHub 
<img width="421" alt="image" src="https://user-images.githubusercontent.com/35297280/185037869-9cb280c2-52a1-476a-8393-a52fe3188ee0.png">

On another note, the `emoji-mart` team expects us to use the `:thumbsup` emoji as `:+1`.

discussion _t

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan Yes let's have thumbsup in the default emojis.

`+1` for emoji is very developer centric point of view.
