### ISSUE TITLE
How to change the text type after having typed it

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#325]
@AbhayVAshokan _a https://www.loom.com/share/84520bd39a074fc6a7d054645ff675df

**Comment by AbhayVAshokan** [comment]
@neerajdotname please have a look:
https://vimeo.com/744086437/0b5e52cd3a

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan https://www.loom.com/share/badd535b0d6841ed8e0438c7b5301506

**Comment by AbhayVAshokan** [comment]
@goutham-subramanyam _a can you please share your thoughts on how it can be best handled?

I can see two instances of bubble menus adding the font size:

**Notion** - dropdown

<img width="641" alt="Screenshot 2022-09-02 at 12 53 23 PM" src="https://user-images.githubusercontent.com/35297280/188081941-30e830d6-2a12-4c40-821e-e82bbe393dbb.png">

**Medium** - buttons

<img width="641" alt="Screenshot 2022-09-02 at 12 53 04 PM" src="https://user-images.githubusercontent.com/35297280/188081984-544c9807-ca4e-4fe9-94c1-dc3200d87b12.png">

**Comment by AbhayVAshokan** [comment]
@goutham-subramanyam similar to the above requirement, it is difficult to convert a block of paragraphs to ordered/unordered list. We'll need a better UI for the Bubble menu as a whole.

cc: @vysaghsekharbb

**Comment by goutham-subramanyam** [comment]
@AbhayVAshokan I think having a dropdown would allow us to have more options without cluttering the bubble menu. 

@vysaghsekharbb Please share your thoughts as well.

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan https://www.loom.com/share/708ffd5fa40e48a99fb5a49ae1dd74f6
