### ISSUE TITLE
Writing experience can be further enhanced

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#328]
https://www.loom.com/share/3cb7866c344e467791c29a9621d26d68

**Comment by AbhayVAshokan** [comment]
Editor design documentation is being prepared by @vysaghsekharbb. Keeping this issue on-hold _t for now. All UI cleanup issues can be taken up together.

cc: @goutham-subramanyam

**Comment by vysaghsekharbb** [comment]
@neerajdotname @AbhayVAshokan 

We need to match the styles of the editor and the actual page. The editor is identical to the page.

I will provide guidelines for spacing and styling.

Thank You.

**Comment by AbhayVAshokan** [comment]
@vysaghsekharbb we've updated neetoEditor to the new design system via #364. I've removed the `on-hold` label on this issue. This can be taken up.

**Comment by vysaghsekharbb** [comment]
@AbhayVAshokan Please refer this screen for the spacing.

https://www.figma.com/file/Osl7GBbBk0iwVMc57366nZ/neetoKB?node-id=4046%3A23038

Preview
![image](https://user-images.githubusercontent.com/86587984/193202620-d4f0465c-b226-4afe-9af4-365693882005.png)

**Comment by neerajsingh0101** [comment]
This looks great. I continue to type every week on substack and I think their editor is pretty awesome. So we can check their editor for inspiration.

**Comment by vysaghsekharbb** [comment]
@neerajdotname While exploring Substack, I thought this feature is interesting.

'Secret draft link'

Please take a look at the screenshot below and let me know what you think of having it implemented in KB.

<img width="654" alt="Screenshot 2022-10-03 at 11 10 18 AM" src="https://user-images.githubusercontent.com/86587984/193508607-bdc2b0b2-86a1-44e6-974d-58a2b59e7b23.png">

**Comment by neerajsingh0101** [comment]
@vysaghsekharbb We have preview and our previews anyone can see. I mean the preview page is not restricted by login etc. So that's like "secret draft link".
