### ISSUE TITLE
The inline code block should end when we put the closing backtick

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#334]
https://www.loom.com/share/1d853075559848658052c8041d58e322

@AbhayVAshokan _a Please take a look into this. Not sure if it's a bug.

**Comment by AbhayVAshokan** [comment]
@yedhink I am not able to recreate the issue in staging or production. The next character is always inserted after the inline code block. I need not use the mouse or the arrow keys to navigate to the end. 
 
![editor](https://user-images.githubusercontent.com/35297280/188812064-5cd2ac0c-7c92-4619-857a-56ad563e7d61.gif)

**Comment by yedhink** [comment]
@AbhayVAshokan https://www.loom.com/share/4b72f47b5d2b4e7d93651c1bcad374a2

**Comment by AbhayVAshokan** [comment]
Agreed. Let me have a look at a proper fix for this.
