### ISSUE TITLE
Code block lines are not getting wrapped or no scroll bar present

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#336]
There should be scroll bar or we should wrap the lines. This seems to be a bug. Needs to be fixed with some priority.

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/31244999/188662078-4907e554-5c81-42cc-af10-4eedd214598a.png">

https://handbook.neetokb.com/articles/showing-availability

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@yedhink would quoted text be better suited for this? Will look into wrapping code blocks on priority.
https://spinkart.neetokb.net/articles/testing-article-june-3

**Comment by AbhayVAshokan** [comment]
Closing the issue here. The change is already present in neetoEditor. The styles overridden by neetoKB results in the lack of code wrapping. Will make the necessary changes in neetoKB along with the PR for updating neetoEditor.
