### ISSUE TITLE
Add Table extension

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#348]
- Tables are a great addition to the editor. There are a large number of options available within the TipTap table extension to customize the table structure.
- A decision has to be taken on the menu UI for both the bubble menu and the fixed menu.

Reference: https://tiptap.dev/api/nodes/table
Figma: https://www.figma.com/file/Ebh2R78Ia9FEVpC4tw6d3N/03-Layouts?node-id=1377%3A2753

cc: @karthiknmenon, @vysaghsekharbb 

**Action Items**

- [x] #627 
- [x] #633
  - The slash commands can insert a 3x3 table
- [x] #634
- [x] Fix known issues:
  - Resizing a single column resizes all columns
  - [x] #652 
- [x] #651

**Comment by AbhayVAshokan** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan Closing the epic since all the sub issues has been completed.
