### ISSUE TITLE
Performance issues while typing in the editor

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#369]
You can go to any project on https://neeto-engineering.neetoplanner.com/ and try to add a comment on any task. 
I sometimes type the full sentence and need to wait for 3-5 seconds to see the text.

**Comment by AbhayVAshokan** [comment]
@sandip-mane can you post a video where this issue is relevant? I am not able to re-create the issue
https://vimeo.com/752923807/5ca323c83e

**Comment by sandip-mane** [comment]
@AbhayVAshokan https://app.usebubbles.com/ovj2CJU3puPs8vZwumk5FE/neeto-editor-consuming-memory

Could be an issue with neetoPlanner too. Let us know 😄

**Comment by AbhayVAshokan** [comment]
Very interesting issue. Let me have a look.

**Comment by Amaljith-K** [comment]
@sandip-mane @AbhayVAshokan 
The performance of neeto editor and useLocalStorage hook are fine: https://app.usebubbles.com/w93ZbVjtBtXse7jaaT7Ngw/performance-slow-down-on-neeto-planner

We need to optimize neeto-planner to minimize un-necessary re-renders to fix this problem.

**Comment by sandip-mane** [comment]
@Amaljith-K thank you for the analysis. We will take it up in neetoPlanner.
