### ISSUE TITLE
Discussion for new design requirements

### ISSUE THREAD

**Issue by amaldinesh7** [neetozone/neeto-editor#41]
I have mentioned a few bugs and suggestions in this [video](https://vimeo.com/648999775/8d7c45b1cd). Please take a look at it.

@johnumarattilbb _a

cc: @labeebklatif , @karthiknmenon , @praveen-murali-ind

**Comment by johnumarattil** [comment]
Hey @amaldinesh7 
I'm working for a client project for now. I'll address the queries once I switch to neeto.

**Comment by johnumarattil** [comment]
@amaldinesh7 @karthiknmenon 
Let's not skip any features we had with older editor? Implement same way as dropdown in the editor panel?

I will share the mocks including downsized editor panel.

**Comment by karthiknmenon** [comment]
@amaldinesh7 Marking this as closed.
