### ISSUE TITLE
Does this repo need to public?

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#411]
If not then let's make it private?

**Comment by AbhayVAshokan** [comment]
@neerajdotname The idea behind keeping this repo public is that this may be useful for the open-source community and may be used by someone outside BigBinary. Moreover, this library can be viewed as an extension of the neetoUI library.

**Comment by neerajsingh0101** [comment]
This repo is private now.

Every time I post a message I don't want to check if this repo is public or private. In many videos we share all kinds of private info.
