### ISSUE TITLE
UX issue with the new version

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#419]
https://www.loom.com/share/f2e865482cdd48ebbcbf40ce6cdbf566

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
Interesting issue. The only recent change is the updation of packages. Let me have a look.

**Comment by AbhayVAshokan** [comment]
This issue is caused by https://github.com/ueberdosis/tiptap/pull/3239. An issue is already raised to track this issue: https://github.com/ueberdosis/tiptap/issues/3335. I'll be subscribing to this issue and check what decision is taken. For now, I'm reverting the version of `@tiptap/sugestion`.
