### ISSUE TITLE
neetoChat integration

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#451]
- [x] #452 
- [x] #465
- [x] #457
- [ ] Add box shadow when focussed.

**Comment by AbhayVAshokan** [comment]
@karthiknmenon this is w.r.t the issue https://github.com/bigbinary/neeto-chat-web/issues/5344

1. Introduce video upload. The upload procedure can be similar to images and they will be inserted inline. If neetoEditor is introduced in neetoCourse, this will also be useful there.
2. The options like canned responses, inserting KB articles, and adding a GIF are neetoChat specific. These can be provided as `children` components or via props.
3. Add `react-router-dom` as peer dependency and build something similar to [neetoChat#TextEditor](https://github.com/bigbinary/neeto-chat-web/blob/main/app/javascript/src/components/commons/Formik/TextEditor.jsx). This will make it much easier to use neetoEditor within formik.
4. When the editor is focussed, we mey provide similar focus styles as a Textarea component via box shadow.

**Comment by karthiknmenon** [comment]
@AbhayVAshokan Sounds good. Can you jot down the development guidelines here? How are we going to proceed with the changes? Is it a new editor type or a menu type? Or are we going to export two different kinds of editors from the package?

**Comment by AbhayVAshokan** [comment]
@karthiknmenon https://vimeo.com/773225652/52b0cf4b2f
