### ISSUE TITLE
Unit testing

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#475]
- [ ] Add unit tests to all the different props available for the `Editor` component.
- [ ] Add unit tests for the `EditorContent` component.
- [ ] Add unit tests for the `FormikEditor` component.
- [ ] Add unit tests for the `Menu` component.
- [ ] Add unit tests for the `Attachments` component.
- [ ] Add unit tests for the `isEditorEmpty` method.
- [ ] Add unit tests for the `substituteVariables` method.

test _t

**Comment by AbhayVAshokan** [comment]
@neerajdotname 

neetoUI and neetoCommonsFrontend have unit tests for the different components. Can we introduce tests in all the frontend nanos as well? This will increase confidence while rolling out breaking changes.

cc: @akhil-gautam

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan Sure. Let's do it. However let's do the work of adding tests only for the nanos that have reached certain maturity status. 

Unlike Rails world where we write unit tests while doing the development here we will take up unit tests of nanos only after a nano is stable.

**Comment by AbhayVAshokan** [comment]
Closing this issue. Will take it up when once major work are complete.
