### ISSUE TITLE
Error when importing Editor - Wheel

### ISSUE THREAD

**Issue by sayoojtmc** [neetozone/neeto-editor#493]
https://www.loom.com/share/9fab98589b144c58b35f0a7cba5edeb1

Error:
`ERROR in ./node_modules/@bigbinary/neeto-editor/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/admin/Documents/Dev/learning/scribble-by-sayooj-surendran/node_modules/@bigbinary/neeto-editor/index.js: unknown Statement of type "ForOfStatement"`

**Comment by yedhink** [comment]
@AbhayVAshokan _a Can you please take a look into this with some priority? Thanks.

**Comment by AbhayVAshokan** [comment]
@sayoojtmc for the time being, please make the following change to `.browserslistrc` file to unblock you from using neetoEditor. 
```diff
defaults
+ IE 11
```

Let me take a look at the core issue. It might be something to do with wheel. I'll get it fixed ASAP.
cc: @yedhink

**Comment by AbhayVAshokan** [comment]
@yedhink I am not able to find a proper solution to fix this issue on wheel. Installing neetoEditor is working fine in all neeto products as well as sample react apps. 

Either adding `IE 11` to the browserslist of wheel or of neetoEditor will solve the issue, but not the right way to proceed. There are solutions to update babel plugins (which yielded no desired results).

**Comment by AbhayVAshokan** [comment]
This will be fixed by https://github.com/bigbinary/wheel/issues/957
