### ISSUE TITLE
Unable to select other tabs when an image from 'Unsplash' is selected

### ISSUE THREAD

**Issue by emmanuelsaykara** [neetozone/neeto-editor#541]
**Description:** 
- If an image is selected from 'Unsplash' option:
- [ ] Back button to go back to 'All Images' page is not added
- [x] User won't directed to any other tab if selected

**Video Reference:** 
- https://vimeo.com/788449518/327adcba97

**Comment by AbhayVAshokan** [comment]
The second part is handled via #538.
@gaagul _a lets add a back button to move to the previous state.
