### ISSUE TITLE
Change Code to Codeblock in fixed editor

### ISSUE THREAD

**Issue by amaldinesh7** [neetozone/neeto-editor#55]
Fix the code block styles as well

<img width="421" alt="Screenshot 2021-11-25 at 3 36 50 PM" src="https://user-images.githubusercontent.com/33386004/143421543-b124ff13-e06c-419f-9659-787d3baf94d4.png">

@labeebklatif _a

**Comment by labeebklatif** [comment]
This is fixed via #56
