### ISSUE TITLE
Add ability to edit Editor content variables

### ISSUE THREAD

**Issue by prasidhprabudhan** [neetozone/neeto-editor#554]
<img width="430" alt="image" src="https://user-images.githubusercontent.com/48003387/212628525-8fda09a9-b2f1-4d46-9d4e-c328a1f16fbd.png">
In the above example, update values in the message box (OrderId, RefundAmount, ReasonForRefund, AmountPaid) whenever the variables are updated.

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@gaagul _a please add an estimate after going through the below video: https://vimeo.com/789630014/d47357a8ed
