### ISSUE TITLE
Fix incorrect tab indentation render in the editor

### ISSUE THREAD

**Issue by vivek-viswam-rv** [neetozone/neeto-editor#561]
https://www.loom.com/share/6488bf78b46f44a3a46b67c47d4adc31

cc: @yedhink

**Comment by yedhink** [comment]
@AbhayVAshokan _a Please take a look into this. Is it because we have defined a tab as 4 spaces in neetoEditor by default? If yes, I think it would be a good addition to show it as well as provide to the ability to change the default tab size.

**Comment by AbhayVAshokan** [comment]
@yedhink the default value for `tab-size` is 8 in HTML. TailwindCSS normalizes it to 4. I'll set the `tab-size` as 2 in neetoEditor styles.

The code snippet is not part of neetoEditor. The tab size for the same needs to be updated from the neetoQuiz side.

**Comment by yedhink** [comment]
@vysakh-m _a

**Comment by vysakh-m** [comment]
@yedhink As part of the ongoing revamp, the code block section will be removed. All the existing data in this section will be moved to the description which supports rich text.
These changes should be reflected by next week, so I would suggest using the codeblock section provided by neeto-editor to include code snippets in the future.

**Comment by AbhayVAshokan** [comment]
@vysakh-m in that case we'll get this fixed in the neetoEditor side and get it rolled out in next week's compliance.
