### ISSUE TITLE
Drag and drop attachments into the editor crashes the site

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#570]
1. Add `addons=["attachments"]` prop.
2. Drag and drop any file into the editor.
3. The entire page crashes.

bug _t

@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan When the pr gets deployed on the neeto-review the app is not crashing when we drop files, Drag and drop is working fine apart from the bug which Sandeep had mentioned. Will this be related to the browser in the local system.

**Comment by AbhayVAshokan** [comment]
I noticed too that it started working magically. Probably the newer version of editor got released mid PR. I'll verify the behavior across browsers and close this issue.

@AbhayVAshokan _a

**Comment by gaagul** [comment]
It is working in firefox, I think it is some issue with the chrome browser.
