### ISSUE TITLE
Revamp the UI for drop zone

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#572]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/35297280/214212929-f2f809a9-6be3-4410-b1b7-55fdb8a4e872.png">

- There must be more contrast to the dropzone.
- The text needs to be styled.

@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan Do you specifically have any color in mind? or can I select a shade of gray from neetoUi Colors.
same with the styles as well?

**Comment by AbhayVAshokan** [comment]
@gaagul please do select two shades of grey (bg and border) that have a good contrast with each other.
