### ISSUE TITLE
Not able to navigate through the emojis using keyboard

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#582]
https://www.loom.com/share/2a92f16533004eb69fa19f4f2b1ae202

bug _t

**Comment by AbhayVAshokan** [comment]
@neerajdotname https://vimeo.com/793585243/b475b77819

**Comment by neerajsingh0101** [comment]
@AbhayVAshokan https://www.loom.com/share/ff4c303c29134d7d9f6e714cba574dfb

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's take this up.
1. Revert the option+arrow key shortcut in emoji suggestion.
2. Show the emoji suggestion popup only when one letter is typed. Else return `null`.
3. Don't show a popup at all when there are no results.
