### ISSUE TITLE
Fix issues with types

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#588]
- [ ] Refer to neetoChat and generalize tooltip types: [Composer.jsx](https://github.com/bigbinary/neeto-chat-web/blob/40e692ae5c1dbce438dc38fa6092025009687253/app/javascript/src/components/Inbox/Messenger/Composer.jsx#L267-L281).
<img width="480" alt="image" src="https://user-images.githubusercontent.com/35297280/215636000-0932139c-7c8e-4bd7-854f-a7c9a407a6ef.png">

- [ ] The `editor` prop in `Menu` should not be string. It should be nullable as well.

https://github.com/bigbinary/neeto-editor/blob/6c83d4be13686f19ef98152525d9efd074163740/types.d.ts#L78

- [x] The `onChangeAttachments` prop should be optional. `variables` prop should be optional. Find other optional props and make necessary changes.

- [x] Add types for `substituteVariables` method.
- [x] Add types for `isEditorOverlaysActive` method.

**Comment by gaagul** [comment]
> * The `editor` prop in `Menu` should not be string. It should be nullable as well.

@AbhayVAshokan Should I specify like `editor: any | null;`

**Comment by AbhayVAshokan** [comment]
@gaagul provide `TiptapEditor` as the type. It is already imported at the top of the file and provided to the other instances of `editor`.
