### ISSUE TITLE
Switch to neeto-deploy for review apps

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#591]

**Comment by AbhayVAshokan** [comment]
@gaagul _a

- We need a `Procfile` and `app.json` to setup the deploy. 
  Refer: https://github.com/bigbinary/bigbinary-website/pull/2595
- Once the PR is merged, use the `neeto-editor` project in neetoDeploy to setup review apps and staging.
- Create a test PR to verify the review apps.
