### ISSUE TITLE
[neeto-chat-web-frontend/production] TypeError: p is not a function 

### ISSUE THREAD

**Issue by akhil-gautam** [neetozone/neeto-editor#600]
Ref: https://github.com/bigbinary/neeto-chat-web/issues/6328

**Comment by AbhayVAshokan** [comment]
@gaagul _a can you please check the stack trace and try to recreate this issue?

**Comment by AbhayVAshokan** [comment]
@gaagul _a can you please check the stack trace and try to recreate this issue?

**Comment by gaagul** [comment]
@AbhayVAshokan I could not recreate this issue, As far as I understood The stack trace provided by honeybadger points to an event when the editor is focused after adding a gif, I tried doing the same and also tried some other scenarios as well but I was not able to recreate this error.

cc: @akhil-gautam

**Comment by AbhayVAshokan** [comment]
@mohitharshan123 _a could you please check if it's something to do with gif? If not please assign it back to me. I'm on PTO. I'll find time to look into it if this is editor related.

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's remove the dependency of `lodash.isplainobject` from neetoEditor. This shouldn't be used. It is still here from some old code. Replace with `ramda` equivalent functions.
