### ISSUE TITLE
Remove unused configuration files like webpack config from projects which use rollup

### ISSUE THREAD

**Issue by gaagul** [neetozone/neeto-editor#603]
Part of: #602 
Example: [neeto-form-frontend](https://github.dev/bigbinary/neeto-form-frontend/blob/main/webpack.config.js)

**Comment by AbhayVAshokan** [comment]
Closing this issue. neetoEditor does not need a Webpack config. But the documentation served through the storybook requires Webpack as a dependency.

cc: @Amaljith-K
