### ISSUE TITLE
Mark function call wrappings of exports as `PURE`.

### ISSUE THREAD

**Issue by gaagul** [neetozone/neeto-editor#607]
Part of: #602
Ref: [Array.js](https://github.dev/bigbinary/neeto-commons-frontend/blob/f4dba1232a75f325830d6c1285776664f07eefa8/src/pure/arrays.js#L15-L25)

**Comment by AbhayVAshokan** [comment]
@gaagul while creating sub-issues for epic issues, add the following line to the top comment

```
Part of #parent-issue
```
