### ISSUE TITLE
Ability to specify file size and types for attachments 

### ISSUE THREAD

**Issue by sheminanto** [neetozone/neeto-editor#608]
- In the `Attachments` component there should be some way to specify the file size limit and allowed file types.

cc: @chiraggshah

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's add props to specify the type and size of uploads. Let's not restrict either of them by default. The restriction should be active if the props are provided.

**Comment by gaagul** [comment]
@AbhayVAshokan Can we add an object named restrictions as a prop which is similar to 
`restrictions: {
    maxNumberOfFiles: 1,
    maxFileSize: 100,
    allowedFileTypes: [],
  }`
or should I stick with having all 3 as different props.

**Comment by AbhayVAshokan** [comment]
Yes, that's a nice idea. Name the prop as `config` for the `Attachments` component and `attachmentsConfig` for the same prop passed via the `Editor` component.
