### ISSUE TITLE
Attachments should support single file upload

### ISSUE THREAD

**Issue by sheminanto** [neetozone/neeto-editor#609]
- The user should only be able to select a single file. (Attachments component)
cc: @chiraggshah

**Comment by AbhayVAshokan** [comment]
@sheminanto can you please share a short video explaining where this will be used and why only a single file be uploaded?

**Comment by chiraggshah** [comment]
@AbhayVAshokan : https://www.loom.com/share/87091dd5e6bb411caf59de5bee6bb9ad

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's pick this up. Add a new prop `isSingle` which accepts a boolean value. It should be `false` by default.
