### ISSUE TITLE
thunderstorm emoji should NOT come before thumsup emoji

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#610]
https://www.loom.com/share/fb20a318663b4d868eee4a91cbdd6bca

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's take up this change. 
1. Create a list of important emojis (thumbs-up ,thumbs-down, rocket, party, smiley, etc).
2. Currently the searched emojis are shown in the order specified by emoji-mart, add a custom sort logic. If the filtered emojis contain the important emojiis, they need to appear in front, else sort them in alphabetic order.

**Comment by neerajsingh0101** [comment]
One more example of the way the order should be https://www.loom.com/share/cb4ee903fdc345d081fc68532d845948

**Comment by AbhayVAshokan** [comment]
@gaagul please add the mentioned heart emojis as well. In addition to this emoji-mart also provides the access to frequently used emojis as well. Please prioritize frequently used emojis for our custom sort function as well.
