### ISSUE TITLE
Improve UI for dynamic variables

### ISSUE THREAD

**Issue by praveen-murali-ind** [neetozone/neeto-editor#611]
Part of https://github.com/bigbinary/neeto-engineering-ui-ux/issues/113

@praveen-murali-ind _a

**Comment by AbhayVAshokan** [comment]
@praveen-murali-ind if this issue is finalized, @gaagul can take this up.

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan Need a confirmation on [this](https://github.com/bigbinary/neeto-engineering-ui-ux/issues/113#issuecomment-1433185136) from the design team.

**Comment by praveen-murali-ind** [comment]
@gaagul _a Could you please take this up.

[Figma design](https://www.figma.com/file/474wSQOaB7hj8jvCnyph2Y/neetoRunner?node-id=65%3A1442&t=jPHqEa7UbTSpnMEH-0)

**Comment by praveen-murali-ind** [comment]
@gaagul @AbhayVAshokan We don’t need to override the default neetoUI dropdown border styles to achieve the design. The color contrast and border styles will be fixed once https://github.com/bigbinary/neeto-ui/issues/1567 is resolved.

Ref - https://github.com/bigbinary/neeto-engineering-ui-ux/issues/113#issue-1570567414

**Comment by gaagul** [comment]
> @gaagul _a Could you please take this up.

@praveen-murali-ind I don't have access to the Figma file yet, Could you please give me access?

**Comment by praveen-murali-ind** [comment]
@gaagul Please check now.

**Comment by gaagul** [comment]
> @gaagul Please check now.

Got it.
