### ISSUE TITLE
Reading experience vs Writing experience

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#658]
https://www.loom.com/share/49ea01941a24434a8be599ab7dea3f9c

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@gaagul _a we need to do the following for this issue:
1. Make the styles in the `EditorContent` and `Editor` consistent with each other. There seems to be significant issues with `Shift + Enter` and `Enter`. The spacing should be consistent with what is provided in neetoKB.
2. We need to update the styles in neetoKB. The font of neetoKB must be updated to support bold. We need to check for similar breaking styles. 

I'll add these to this list and let's take it up next week.
