### ISSUE TITLE
Preview of text while hovering the different sizes available on the welcome screen

### ISSUE THREAD

**Issue by andrewperayil** [neetozone/neeto-editor#660]
Description: While changing the size of contents given in description we are not able to see preview of the sizes while hovering the different sizes available.

Video Reference: https://www.loom.com/share/3c30765056a74d71be1e7dd7fe7d7e4b

Cc: @praveen-murali-ind @chiraggshah

**Comment by AbhayVAshokan** [comment]
If I understood correctly, the form preview should update when the dropdown item is hovered. IMO It wouldn't be a good idea from the UX perspective. I believe other editors too don't follow this pattern.

Perhaps, we can update the dropdown itself in such a way that there are visual cues on what the size would be. For example, the "Heading 1" can be in a larger font. We'll try it out and see whether it improves the UI.
