### ISSUE TITLE
The link property is working even if we break the content which had the link

### ISSUE THREAD

**Issue by andrewperayil** [neetozone/neeto-editor#661]
Description: When the content containing the link is separated as two words, the link is still accessible from both words.

Video Reference: https://www.loom.com/share/88ac47fa162f47c4b07cda94a4a7d13d

Cc: @chiraggshah

**Comment by AbhayVAshokan** [comment]
This is the default behavior of WYSIWYG editors so not a bug. You can refer to how [trix editor](https://trix-editor.org/) does it. Hence, not taking this up.
