### ISSUE TITLE
Fix issue with quotes

### ISSUE THREAD

**Issue by yashjk** [neetozone/neeto-editor#709]
I have described the issue in the recording provided below
https://www.loom.com/share/377caebec49740d5a1216bc9d2256656

**Comment by yashjk** [comment]
bb-academy _t

**Comment by AbhayVAshokan** [comment]
@yashjk _a please share your thoughts on https://vimeo.com/811288957/f8437d9376

@gaagul let's take up the second part of the issue discussed in the video. Add a "Code Block" option in addition to the "Code" in the menu.

**Comment by yashjk** [comment]
@AbhayVAshokan I checked and using quotes for any  quotes(```) is solving the problem for me. Thanks
