### ISSUE TITLE
Issue with slash command options

### ISSUE THREAD

**Issue by Prasannams97** [neetozone/neeto-editor#718]
Please ref: https://www.loom.com/share/6a4114fdcf45464aaee55b0b2c550985

**Comment by Prasannams97** [comment]
bug _t

**Comment by AbhayVAshokan** [comment]
@gaagul _a interesting issue. Let's take this up.

**Comment by AbhayVAshokan** [comment]
@gaagul we can conditionally render the slash commands within the `render` method of `SlashCommands/ExtensionConfig.js`. See if it is possible to check which node is currently focussed. If it is a `figcaption` tag, return `null`. Else return the current logic.

**Comment by sumanranjanpanda** [comment]
@gaagul any update on this?

**Comment by gaagul** [comment]
@sumanranjanpanda This an edge case in titptap package that we use as core for out neetoEditor, Once an extension is added to the editor instace it will be recogonized in all the editor nodes and "image" is a node in editor.

I need to look into the code structure of the "suggestions" plugin which is used to render the commands and find if there is a possible way of overriding the behaviour of slash commands in "image" node. I will give a conclusion about this issue by the end of this week.
