### ISSUE TITLE
Retain text highlighting when adding links 

### ISSUE THREAD

**Issue by navaneethsdk** [neetozone/neeto-editor#745]
When adding a link in the editor, the current behavior removes any highlighting that may have been applied to the text. The proposed solution is to retain the text highlighting when adding links in the editor. 

https://app.usebubbles.com/eMPQh6xF73vwm5i8NU5udc/retain-text-highlighting-when-adding-links

@AbhayVAshokan _a
cc: @yedhink

**Comment by AbhayVAshokan** [comment]
Agreed this needs to be fixed. @gaagul _a let's take this up.
