### ISSUE TITLE
<action-text-attachment/> not rendered in FormikEditor

### ISSUE THREAD

**Issue by adityamahajan-io** [neetozone/neeto-editor#753]
Please have a look at this video: https://app.usebubbles.com/pJHmq3o1FtBKjRvDpLN2cG
This is the case for some of the questions in neetoQuiz where images are being rendered in `EditorContent` component but not in `FormikEditor`

**Comment by AbhayVAshokan** [comment]
Closing by virtue of https://github.com/bigbinary/neeto-quiz-web/issues/2146
