### ISSUE TITLE
Images are shrinked in editor in safari browser

### ISSUE THREAD

**Issue by shindeniranjan** [neetozone/neeto-editor#754]
https://vimeo.com/817159210/9b7f2c70e7

**Comment by AbhayVAshokan** [comment]
@shindeniranjan can you please share the URL to the published article so that we can verify the same on our end? I am not able to recreate this issue.

**Comment by shindeniranjan** [comment]
@AbhayVAshokan The issue is happening in neeto editor only, on published page it is working as expected.
published kb : https://chattest3.neetokb.com/articles/test-prod-2
neeto editor: https://chattest3.neetokb.com/admin/articles/test-prod-2/edit

**Comment by AbhayVAshokan** [comment]
Interesting issue. @gaagul _a please take a look.

**Comment by AbhayVAshokan** [comment]
@shindeniranjan we are not able to recreate this issue today. Can you please verify if the issue in the shared link is still present? If so, please add gaagul.gigi@bigbinary.com as a member so that we may debug the issue in detail.

**Comment by shindeniranjan** [comment]
@AbhayVAshokan the issue is not reproducible now.

**Comment by AbhayVAshokan** [comment]
Closing this as completed. It might be caused due to interference from any other neeto product. We'll continue the discussion if it comes up again.
