### ISSUE TITLE
Image layout enhancement

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#756]
Ref: https://app.usebubbles.com/ikz37gvuWY5SoHQpUpfomo/image-layout-issues

https://github.com/bigbinary/neeto-kb-web/issues/4032

**Comment by gaagul** [comment]
@sandip-mane https://www.loom.com/share/8dee6e0e9ba24c0b9df6ac66c5167e2b Please have a look at this video, neetoEditor has a feature to resize the uploaded images I think this will solve the issue with visibility of uploaded images.

**Comment by sandip-mane** [comment]
@gaagul awesome, was not aware of it. Please close the issue if no changes are needed.
