### ISSUE TITLE
Editor issues in attachments on neetoDesk

### ISSUE THREAD

**Issue by VarunSriram99** [neetozone/neeto-editor#771]
**Bug**
When attaching a file to the editor, the attached file is not displayed on the editor until a text change on the editor.

**Steps to reach the page and recreation**
- [Tango Link](https://app.tango.us/app/workflow/Attachment-bug-in-description-editor---New-ticket-c80b33806b124ae88dabb5ac936fcc74)
- [Video link](https://app.usebubbles.com/ptLcHJWjUHtvtG9EUmvyKF/neeto-desk-new-ticket-editor-bug)

**Additional description**
A similar editor in neetoDesk when following this path - Login > Tickets > *Select a ticket* > *Click on Reply* > Reply editor - doesn't seem to have this issue.

bug _t caught-by-cypress _t

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
This issue will be solved in PR:https://github.com/bigbinary/neeto-desk-web/pull/16389

**Comment by gaagul** [comment]
Closing the issue.

cc// @AbhayVAshokan
