### ISSUE TITLE
Syntax highlighter truncates code into single line

### ISSUE THREAD

**Issue by anil-anand** [neetozone/neeto-editor#772]
There is an issue when the code block in `EditorContent` is showing an array of objects.
Video: https://app.usebubbles.com/qaB62dc98WWy4yZkeGkAtS/syntax-highlighter-issue-in-editor-content

@AbhayVAshokan _a
Please have a look into this.

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's take this up this week. This is a priority _t issue. When we closely inspect the code block of `Editor` and `EditorContent` there are differences in styles. The `Editor` component wraps the lines using a `whitespace: pre-wrap` style. 

Use the code snippet provided in https://github.com/bigbinary/neeto-quiz-web/issues/2412 for testing the same.
