### ISSUE TITLE
Prevent rendering of links with malicious href attributes in `EditorContent`

### ISSUE THREAD

**Issue by ajmaln** [neetozone/neeto-editor#783]
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/434

Fix XSS caused by rendering anchor tags with `javascript:` protocol URLs.

We can use util like the below to get safe URLs:

```js
const getSafeURL = (url) => {
   const parsed = new URL(url);
   if (parsed.protocol !== 'https:') return;

   return url;
}
```

**Comment by ajmaln** [comment]
This might not be an issue in neetoEditor, while verifying found that we were using `HTMLReactParser` for rendering the editor content in form which doesn't sanitize the HTML string. Please verify and close the issue.

**Comment by AbhayVAshokan** [comment]
@gaagul _a can you please verify this once and close it if it is not relevant?

**Comment by gaagul** [comment]
@AbhayVAshokan We are sanitizing the content before displaying using `EditorContent`,
Reference: https://github.com/bigbinary/neeto-editor/blob/88fb3bbee6964472045539c9320c562fced7bcfb/src/components/EditorContent/index.jsx#LL24C1-L26C9
