### ISSUE TITLE
Vertical gap issue 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#787]
@AbhayVAshokan @praveen-murali-ind @philson-philip 
https://www.loom.com/share/fefc631e7e7c481b9913aa1ca2e5d662

https://neerajdotname.neetokb.com/articles/europe-2023-trip
https://www.notion.so/Neeraj-Summer-2023-trip-e39e36a68aeb4005b7bf0f4e67420324

**Comment by philson-philip** [comment]
@philson-philip _a I will compare the editor styles for `notion` and `neeto-editor` and update the necessary changes in `neeto-editor`.

cc: @praveen-murali-ind

**Comment by neerajsingh0101** [comment]
https://www.loom.com/share/4c864bd06eb94fd78923ce13d619bf6d
