### ISSUE TITLE
Another take at the icons in the tool bar

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#788]
@AbhayVAshokan @vysaghsekharbb @praveen-murali-ind https://www.loom.com/share/bd44c0eb0f9148d3be6d29b54fcc6596

**Comment by AbhayVAshokan** [comment]
@philson-philip _a please have a look.

**Comment by vysaghsekharbb** [comment]
@neerajdotname We updated the background color and spacing to improve the icons after a meeting between me and Philson. 

@philson-philip Please update a screenshot here.

**Comment by philson-philip** [comment]
@vysaghsekharbb 
<img width="1368" alt="Screenshot 2023-06-20 at 11 32 15 AM" src="https://github.com/bigbinary/neeto-editor/assets/22117214/5c13b4c0-dc1a-41f3-8f79-e404fb89ba5d">
