### ISSUE TITLE
Rename attachment option triggers form submit

### ISSUE THREAD

**Issue by VarunSriram99** [neetozone/neeto-editor#790]
Video link: https://app.usebubbles.com/mr8SwP61PwmfaxsJzh88bP/neeto-editor-bug-in-neeto-desk-edit-page
Tango link: https://app.tango.us/app/workflow/Bug-in-neetoEditor-attachment-rename-dd3d9f30de414b8ab96dc4cdee68abd5

Description

When renaming an attachment in the editor on a form which submits on pressing enter, the form is submitted along with the rename operation.

**Comment by VarunSriram99** [comment]
@AbhayVAshokan _a Please take a look at this.

CC: @ajil-paul 

bug _t caught-by-cypress _t

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@VarunSriram99 This issue will be fixed in the next compliance release.

CC: @ajil-paul
