### ISSUE TITLE
Room for improvement

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#793]
The published version looks good. https://neeto-engineering.neetokb.com/articles/build-reusable-shared-modules

The editing version looks messy. https://neeto-engineering.neetokb.com/admin/articles/build-reusable-shared-modules/edit

https://monosnap.com/file/VphR6gke7ovUg4OBHedZRUy81rIHqH

Please refer to how notion might handle the same case and if something can be done then let's do it.

**Comment by AbhayVAshokan** [comment]
@philson-philip _a please have a look.
