### ISSUE TITLE
Increasing the contrast

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#794]
@praveen-murali-ind @philson-philip https://www.loom.com/share/1a5b58bbafbc4f9e9995a873a23ceaa7

https://neetokbhelp.neetokb.com/admin/articles/domain-level-redirection/edit

https://gist.github.com/neerajdotname/6226b85f223ba50bb30bd7f5164dab86

**Comment by praveen-murali-ind** [comment]
@praveen-murali-ind _a
