### ISSUE TITLE
Code blocks have horizontal scroll on mobile screens

### ISSUE THREAD

**Issue by adityamahajan-io** [neetozone/neeto-editor#797]
https://app.usebubbles.com/uxhieRfYcXtwbbGPCDUzV2/code-blocks-issue
Original issue: https://github.com/bigbinary/neeto-quiz-web/issues/2571

Long lines in codeblocks have horizontal scroll on both mobile and desktop screens
<img width="685" alt="Screenshot 2023-06-07 at 2 18 49 AM" src="https://github.com/bigbinary/neeto-editor/assets/66865722/6e59c31c-18b9-43a7-917d-07faa2c4799e">

Normal code blocks have horizontal scroll on mobile screens
<img width="366" alt="Screenshot 2023-06-07 at 2 29 11 AM" src="https://github.com/bigbinary/neeto-editor/assets/66865722/38e300be-2530-4183-b64b-c9819b24da1b">

@AbhayVAshokan _a Could you please have a look into this?

**Comment by AbhayVAshokan** [comment]
~@AbhayVAshokan~ @adityamahajan-io   _a please have a look at his video and let me know if any changes are needed on the neetoEditor end: https://vimeo.com/834032833/8288e19291

**Comment by adityamahajan-io** [comment]
@AbhayVAshokan Thanks for the video. I will add container widths explicitly and that should solve the issue. However, in case of overflowing code blocks, can we have `visible` scrollbars? This would help convey to the consumer that there is more content to be seen. Right now, the consumer might miss horizontally scrolling the code block and could attempt the question incorrectly based on incomplete information shown.

This would be a good addition in general, not only for the use case of neetoQuiz.

**Comment by AbhayVAshokan** [comment]
`overflow: auto` will add a scrollbar whenever there is an overflow of the content. The scrollbars are visible by default. MacOS hides it for aesthetic purposes. You may verify the same by updating the same in settings:

<img width="697" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/35297280/e43af726-bf41-4777-8742-0b6367ac3aea">

**Comment by AbhayVAshokan** [comment]
@adityamahajan-io can we close this issue now?

**Comment by adityamahajan-io** [comment]
@AbhayVAshokan Yes, this can be closed. I have fixed it in quiz as per your suggestion and it works now. Thanks!
