### ISSUE TITLE
All links should be opened in new tabs

### ISSUE THREAD

**Issue by adityamahajan-io** [neetozone/neeto-editor#798]
Ref: https://github.com/bigbinary/neeto-quiz-web/issues/2603
While attempting the [Ramda quiz](https://neeto-engineering.neetoquiz.com/quizzes/pure-utility-functions) by neeto-engineering team, clicking on links in answer explanation is opening links in the same tab. 

This is an issue because navigating away from the current path while attempting a quiz leads to `attempt termination`. 
Can we handle this case where links that are copy-pasted into neetoEditor also have a `target="_blank"` attribute similar to links which are embedded using editor options?

<img width="1400" alt="Screenshot 2023-06-07 at 2 59 31 AM" src="https://github.com/bigbinary/neeto-editor/assets/66865722/1ed73c81-358a-4fbb-818c-36e5ef67c9b6">

@AbhayVAshokan _a Could you please have a look into this on priority? Since more folks would be attempting this quiz in the coming days.

**Comment by AbhayVAshokan** [comment]
@gaagul _a please have a look at this issue. Create a fresh quiz in the staging environment and check why links are opening in the same tab.

**Comment by Amaljith-K** [comment]
@gaagul this is causing issues in neetoQuiz as well: https://github.com/bigbinary/neeto-quiz-web/issues/2603
I'm bumping up it to high-priority

**Comment by adityamahajan-io** [comment]
In case of neetoQuiz answer explanation, I did some testing and found that the behaviour is changing based on whether we are rendering `question.explanation.body` vs `question.explanation.body.to_s`. It is working as expected and opening links in new tab when rendered using `question.explanation.body` instead of `.to_s` so I'm adding a fix for it in neetoQuiz.
This issue can be closed if the above behavior is intentional. 

Removing the priority tags for now.
cc: @Amaljith-K @AbhayVAshokan @gaagul

**Comment by gaagul** [comment]
During discussion with @adityamahajan-io , we identified a problem related to the `to_s` method being called on the editor content from the controller before passing it to the front end. It appears that this conversion is removing the target="_blank" attribute from the HTML `a` tag.

cc: @Amaljith-K

**Comment by gaagul** [comment]
Closing this issue since this will be fixed in PR: https://github.com/bigbinary/neeto-quiz-web/pull/2610
