### ISSUE TITLE
Paragraph dropdown `strategy` prop needs to be set to `fixed`

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#825]
The strategy prop of the paragraph dropdown has its default value which is `absolute`. This is creating some extra scroll and height when the dropdown is opened in a congested area. There's a similar problem in the comments part of neetoPlanner. Please refer to the screenshot for more details.

Ref: https://github.com/bigbinary/neeto-planner-web/issues/4079#issuecomment-1619636491

@AbhayVAshokan  could you please check?

<img width="1285" alt="image" src="https://github.com/bigbinary/neeto-editor/assets/8749438/a1bb4468-7589-44c1-807d-c1a2bc3644fe">

**Comment by AbhayVAshokan** [comment]
@gaagul _a please provide strategy as "fixed" for the font size dropdown.
