### ISSUE TITLE
Code block UI amendment required

### ISSUE THREAD

**Issue by navaneethsdk** [neetozone/neeto-editor#827]
Please refer to the following video for more information
- UI issues: https://vimeo.com/842749776/8e3360680b

@AbhayVAshokan _a
cc: @yedhink 

---

**Action items**

- [x] Saving a codeblock converts certain characters to `&lt;`, `&gt;`, etc.
- [x] Remove text wrapping from the CodeBlocks in edit mode.
- [x] Fix the position of copy button when the content scrolls.
- [x] Verify the behaviour of dropdowns during scroll.
- [x] Remove `auto` highlight and make `plaintext` by default.

**Comment by navaneethsdk** [comment]
Also, I would like to know how the syntax highlighting works for the type `auto`. Is it supposed to automatically detect the syntax type? If it is supposed to be a general syntax type, I don't think it's serving its purpose very well. I believe the intended purpose of the general syntax type is not being fulfilled since certain words in my plaintext or markdown document are highlighted incorrectly in the `auto` mode.

**Comment by AbhayVAshokan** [comment]
@navaneethsdk 

- The copy button in the edit mode is added referring to the Notion style. We can think of hiding in the future it if it causes inconviniences.
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/d072db85-f99b-4b4b-a41b-dcab0a648bbe)

- Agreed that the scroll behaviour is not consistent for edit mode and display mode. The ideal behaviour for code blocks is not letting the text to wrap. We'll be adopting this behaviour as well. Here are a screenshots from GitHub and Notion for reference. CodeBlock may not be the ideal block to write descriptive content. LMK your thoughts on this:
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/29c96e7e-ef40-496f-90ad-e0ad951c072c)
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/805cebee-9e14-4c0f-bd2a-b9c3ec7b6505)

- I agree that the auto syntax highlighting is not perfect. Let's adopt the GitHub style for this case. If \`\`\` is provided, let it default to `paintext`. Language may be selected either by the dropdown, or by directly typing something similar to  \`\`\`javascript.

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's take this up.

**Comment by gaagul** [comment]
> Also, I would like to know how the syntax highlighting works for the type `auto`.

@navaneethsdk  When the type is `auto` the syntax highlighting is done by the "hljs" library, The "hljs" library has "highlightAuto" function which internally determine the most suitable language for syntax highlighting by parsing the provided content and selecting the language with the highest preference based on specific indexes.

If a language is specified, "hljs" has a function which is "highlight" which has a second arugument to specify language.

**Comment by navaneethsdk** [comment]
@AbhayVAshokan 

> The copy button in the edit mode is added referring to the Notion style. We can think of hiding in the future it if it causes inconviniences.

Got it. I found no harm in having the copy button in the edit mode. We can keep it as it is for now.

> The ideal behaviour for code blocks is not letting the text to wrap. We'll be adopting this behaviour as well. Here are a screenshots from GitHub and Notion for reference.

I see. That makes sense given that the intended input for a code block is code after all. But for the `plaintext` type, at least, I found text wrapping very readable in the view mode. I would say neither GitHub nor Notion has done a great job in that arena. I believe that by providing an option for users to type in `plaintext`, we are in turn giving them an opportunity to write descriptive content without them manually having to add a newline character after each line. So would it be feasible to incorporate text wrapping for the `plaintext` at least? Lemme know your thoughts.

> I agree that the auto syntax highlighting is not perfect. Let's adopt the GitHub style for this case. If ``` is provided, let it default to plaintext. Language may be selected either by the dropdown or by directly typing something similar to ```javascript.

Sounds great to me.

---


@gaagul 
> When the type is auto the syntax highlighting is done by the "hljs" library, The "hljs" library has "highlightAuto" function which internally determine the most suitable language for syntax highlighting by parsing the provided content and selecting the language with the highest preference based on specific indexes.

I see. I would rather recommend that the editor defaults to `plaintext` as Abhay pointed out. It is better to have no highlighting in the code block (which is the case with `plaintext`) than to have an incorrect highlighting from `hljs`.
I believe the `auto` type from `hljs` would be more suitable for a code editor than a general-purpose text editor.

**Comment by AbhayVAshokan** [comment]
> I believe that by providing an option for users to type in plaintext, we are in turn giving them an opportunity to write descriptive content without them manually having to add a newline character after each line. So would it be feasible to incorporate text wrapping for the plaintext at least?

This seems like a good idea. The only drawback being the drastic changes in the UI (text wrapping) whenever the user toggles from `plaintext` to any other language. @gaagul can you check the feasibility of this implementation as well?

**Comment by gaagul** [comment]
> >  @gaagul can you check the feasibility of this implementation as well?

Yes, I will take a look at  the feasibility of adding this change.

**Comment by AbhayVAshokan** [comment]
We'll try keeping the text wrapping in both edit and display mode for now. This seems like the right choice for our use cases. A horizontal scrollbar is less user-friendly.
