### ISSUE TITLE
Controlling text 

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#828]
https://www.loom.com/share/d6f1ed814d2742d0929ffc818796e7ab

https://neetoformhelp.neetokb.com/admin/articles/google-sheets/edit

**Comment by AbhayVAshokan** [comment]
@gaagul _a please check this issue.

**Comment by gaagul** [comment]
@neerajdotname @AbhayVAshokan The heading node and the paragraph node in the content somehow got merged into one node, I have made changes to the article and the issue is solved, Please take a look at the article, I will close the issue once confirmed.

**Comment by AbhayVAshokan** [comment]
@gaagul try to re-create this issue on our side. We need to understand what caused this issue.

**Comment by gaagul** [comment]
> @gaagul try to re-create this issue on our side. We need to understand what caused this issue.

I tried recreating the issue from our side and could not do so, That was why i looked into the article itself. I will try different approaches to recreate it.

**Comment by gaagul** [comment]
Closing the issue.
