### ISSUE TITLE
Improve the UI for image captions

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#830]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/4510

- [x] Reduce the font size of the caption to 13px.
- [x] Change the font color of the caption to `neeto-ui-gray-500`.

![image](https://github.com/bigbinary/neeto-editor/assets/35297280/1ef0b0fc-eee7-4fcd-b272-6282ccb1f62b)

@gaagul _a

cc: @praveen-murali-ind let us know if this is looks good to you.

**Comment by neerajsingh0101** [comment]
This looks great. 😍

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan Looks good to me 👍
