### ISSUE TITLE
Issue with images

### ISSUE THREAD

**Issue by praveen-murali-ind** [neetozone/neeto-editor#841]
@AbhayVAshokan @gaagul I have checked a few articles on [headstrong-pro.neetokb.com](https://headstrong-pro.neetokb.com/categories/getting-started) and found some issues with the articles that contain images. This is not happening for newly created articles. Could you please look into this issue?

![screencapture-headstrong-pro-neetokb-articles-the-link-for-the-back-end-system-expired-what-do-i-do-2023-07-24-18_54_25](https://github.com/bigbinary/neeto-editor/assets/48869249/09f5dc2b-e326-43e3-92c0-230ba60b16ba)

**Comment by AbhayVAshokan** [comment]
@gaagul _a we should write a rake task (data migration) to make sure all these images are properly contained. We should restrict the height/width of these images accordingly.

**Comment by gaagul** [comment]
The Migration has been merged in neeto-kb-web. https://github.com/bigbinary/neeto-kb-web/pull/4630, hence closing closing the issue.
