### ISSUE TITLE
The fixed menu styles are broken

### ISSUE THREAD

**Issue by AbhayVAshokan** [neetozone/neeto-editor#855]
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/073baf00-b125-46f8-b138-3c4f5755e2f9)

It is possible to manually decide which addons to use using the `defaults` prop. The separator should be conditionally rendered so that  unnecessary separators are not introduced. Here is a screenshot from neetoSite.

@gaagul _a this is a priority _t issue. 
bug _t

**Comment by gaagul** [comment]
@AbhayVAshokan This will be taken up in #854
