### ISSUE TITLE
Getting out of number ordered and unordered list

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#861]
https://www.loom.com/share/1528557c64a846c0addb29919ea454b8

**Comment by AbhayVAshokan** [comment]
@gaagul this issue is pretty hard to reproduce. Doesn't happen all the time. I could only reproduce it once after using neetoKB for some time. But I am not fully sure how to reproduce it. Can you please check if there are issues in Tiptap for this flaky behavior?

**Comment by gaagul** [comment]
> @gaagul this issue is pretty hard to reproduce. Doesn't happen all the time. I could only reproduce it once after using neetoKB for some time. But I am not fully sure how to reproduce it. Can you please check if there are issues in Tiptap for this flaky behavior?

I will look into it.

**Comment by gaagul** [comment]
Closing this issue since I am not able to reproduce it.
cc: @AbhayVAshokan
