### ISSUE TITLE
Add callback support for mention event

### ISSUE THREAD

**Issue by divyajomi08** [neetozone/neeto-editor#868]
We need callback support for the mention event in neeto-editor. This will enable the host application to dynamically update the mention array as needed, eliminating the requirement to pass the entire array initially.

Ref: https://github.com/bigbinary/neeto-planner-web/issues/4322

cc: @AbhayVAshokan @sandip-mane

**Comment by AbhayVAshokan** [comment]
@gaagul _a https://vimeo.com/856730242/76823206b6

**Comment by sandip-mane** [comment]
@AbhayVAshokan @gaagul we have skipped this requirement from neetoPlanner. It will be okay to not implement it.

**Comment by AbhayVAshokan** [comment]
In that case, let's not implement it right now. The implementation is complex and requires a lot of effort.
