### ISSUE TITLE
`FormikEditor` not re-rendering on change in variables

### ISSUE THREAD

**Issue by vishnuMohanan01** [neetozone/neeto-editor#869]
https://github.com/bigbinary/neeto-editor/assets/44225503/5f92edce-d459-4d46-918e-d769e012462d

## Some useful links

1. Usage of `shouldUpdate` prop in FastField: https://github.com/jaredpalmer/formik/blob/41720c2f69407e41c27b325923bce63436b07f45/packages/formik/src/FastField.tsx#L76C20-L76C31
2. Sample use case in `neeto-approvals-frontend`: https://github.com/bigbinary/neeto-approvals-frontend/blob/75c31e321d28b19bad2b25b36960e9fc681230ea/src/components/Approvals/Templates/DynamicBlock.jsx#L57
3. FastField doc: https://formik.org/docs/api/fastfield

**Comment by gaagul** [comment]
@gaagul _a
