### ISSUE TITLE
Allow redirecting to clickable ink's url from the Editor itself

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#871]
https://www.loom.com/share/ad9702dc05fd4668be7de9fc0ddbf0c0

@AbhayVAshokan _a Please look into this and assign to someone if we can take it up.

**Comment by AbhayVAshokan** [comment]
This is a convenient requirement. 
@gaagul _a let's take this up. Let's show a Tippy popup with a clickable link similar to SubStack. Refer: https://github.com/bigbinary/neeto-editor/issues/874
