### ISSUE TITLE
Feature request for adding dos and don'ts blocks

### ISSUE THREAD

**Issue by praveen-murali-ind** [neetozone/neeto-editor#875]
@neerajdotname @AbhayVAshokan In [neetix](https://neetix.neetokb.com/articles/confirmation-modal-best-practices), we will have to add more dos and don'ts blocks while creating documentation of UI/UX topics. Please LMK your thoughts on implementing something similar to https://primer.style/design/guides/accessibility/links#guidelines.

<img width="1440" alt="Screenshot 2023-09-01 at 7 25 21 PM" src="https://github.com/bigbinary/neeto-editor/assets/48869249/41931c92-dd42-40a8-b06a-90eb7c39deda">

**Comment by praveen-murali-ind** [comment]
@neerajdotname _a

**Comment by AbhayVAshokan** [comment]
@praveen-murali-ind _a we could achieve a similar UI using a table. Please have a look at: https://abhay-ashokan.neetokb.com/articles/do-s-and-don-ts

In this example, I inserted images within individual cells. We can also insert the texts "Do" and "Don't" for this requirement. Please check if this would suffice.
![image](https://github.com/bigbinary/neeto-editor/assets/35297280/624c9445-df26-42c8-ac2f-2273825f507b)

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan Yes, we can achieve a somewhat similar UI using a table. However, there are some key reasons why a table may not be the best fit for this particular requirement:

- **Dos and don'ts blocks don't require borders**: Tables often come with visible borders around cells, which might not be suitable for the clean and borderless design required for dos and don'ts.

- **Lack of mobile responsiveness**: Tables tend to maintain their layout structure on mobile devices, which can lead to usability issues. In smaller viewports, dos and don'ts blocks should be able to collapse vertically.

- **Dual layout requirements**: To effectively present dos and don'ts, we need two basic layouts – a **horizontal layout** for smaller images and a **vertical layout** for full-screen images. Achieving this flexibility within a table structure may be challenging and result in a less intuitive user interface.

**Comment by AbhayVAshokan** [comment]
@praveen-murali-ind please LMK if this looks good to you.

After looking into the different possibilities here's my conclusion on building a non-confusing UI. We shall add a new option within the table to toggle it into a do's and don'ts block.

**Implementation**
- Add an option to toggle between the two table states in the table menu.
- Add an attribute `data-dos-and-donts` to the `table` element if the option is toggled.
- If the `table` element has this particular attribute, use SCSS selectors to hide all borders. Use media query to change the layout of the table in smaller screens.

**Comment by praveen-murali-ind** [comment]
@AbhayVAshokan Let’s use `div` instead of `table` for the less confusing user interface.

**Comment by AbhayVAshokan** [comment]
@praveen-murali-ind I agree that `div` would be the semantically correct choice for the DOM element. But, looking from the implementation perspective, we would need to architect an entirely new extension and a new option in the menu bar for this particular change. The new extension will be really specific for this particular purpose and will look like a duplicate of the Table extension. I would suggest that we don't overengineer this requirement since it is specific to neetoKB.

**Comment by neerajsingh0101** [comment]
I'm putting this PR and the issue on-hold _t. I'll discuss my queries with @praveen-murali-ind whenever I've next call with him and will discuss it. In short I have some questions about the requirement itself.

**Comment by praveen-murali-ind** [comment]
Closing this issue and [draft PR](https://github.com/bigbinary/neeto-editor/pull/880) based on the discussion with @neerajdotname. We'll revisit it later when the 'Edit this page on GitHub' feature is implemented in the KB.
