### ISSUE TITLE
Parsing issues when content is wrapped in multiple div tags

### ISSUE THREAD

**Issue by abilash-sajeev** [neetozone/neeto-editor#878]
Sometimes the information we receive via emails is wrapped inside multiple `div` tags. There are parsing issues when this content is passed to the `neeto-editor`.
 - [ ] Extra blank lines are inserted while editing
 - [ ] Leading whitespace is added to each `<div>` tag content

`Initial content`
![MS to Gmail mailbox](https://github.com/bigbinary/neeto-editor/assets/35305344/9d2ecbf8-7770-4025-9a20-736e2efcf3b6)

`Edit view`
<img width="1680" alt="Parsing issue for content wrapped in multiple div tags" src="https://github.com/bigbinary/neeto-editor/assets/35305344/b520a45b-4fdd-48c3-8252-a6b68ddf9843">

**Comment by gaagul** [comment]
@gaagul _a

**Comment by gaagul** [comment]
Parsing and removing div tags internally is not be a good approach, since we have nodes like image and video which have wrappers as div, this change will affect the internal node structure of editor.

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@abilash-sajeev please share some text content so that we have an idea of the issue we are dealing with.

**Comment by gaagul** [comment]
> Parsing and removing div tags internally is not be a good approach, since we have nodes like image and video which have wrappers as div, this change will affect the internal node structure of editor.

I missed a point, Also the text content inside div will be parsed as "p" tag inside editor.

**Comment by abilash-sajeev** [comment]
@AbhayVAshokan the following content can be used to recreate the above scenario.

```
const content = '<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\nHi Team,</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\n<br>\r\n</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\nI am unable to generate invoices. Please check.</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\n<br>\r\n</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\n<br>\r\n</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\nThanks,</div>\r\n<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);" class="elementToProof">\r\nAdam<br>\r\n</div>';
```

cc: @gaagul

**Comment by AbhayVAshokan** [comment]
As discussed, extract the `transformCommentForEditor` method to neetoEditor. Once done, please roll it out to neetoDesk. The new method should be named as `transformEditorContent`.

minor _t
