### ISSUE TITLE
Allow applying same styling as `<p>` tag for other tags too when it comes to text

### ISSUE THREAD

**Issue by yedhink** [neetozone/neeto-editor#887]
https://www.loom.com/share/afce51f4b3fd4af791f1ad9fc5651af1

@AbhayVAshokan _a Please look into this and assign to someone if this is doable.

**Comment by sandip-mane** [comment]
The spacing issue that @yedhink mentioned is also due to the `div` tags, ref: #878

**Comment by sandip-mane** [comment]
IMO, neetoEditor (preview styles) can consider the `div` and `p` tags the same way to fix this issue.

**Comment by AbhayVAshokan** [comment]
@gaagul _a let's take this up. We need to apply the same styles as the `p` tag to the `div` tags of this pattern. A small change to SCSS should do.

minor _t

**Comment by sandip-mane** [comment]
We might need to check this thoroughly though, sometimes, we might receive nested `div`s or `p` tag inside `div`.

**Comment by gaagul** [comment]
@AbhayVAshokan  https://gaagul-gigi.neetorecord.com/watch/b78ee151-bb37-4428-b13e-e581dad5b063
This is the issue behind the different styles and i have also discussed about the solution in the video.

**Comment by AbhayVAshokan** [comment]
@gaagul: yes, let us proceed to fix the issue using SCSS. Since images are also using `div`s, verify that it does not break anything for images.
