### ISSUE TITLE
Is it possible to pass data attributes to the contentEditable `div`?

### ISSUE THREAD

**Issue by ajmaln** [neetozone/neeto-editor#897]
We have an issue in neetoForm due to Grammarly extension interfering with the scrolling while a neeto-editor is in focus. One way to solve it is to add few data-attributes to the content editable div. Is it possible to do from neeto-editor?

@AbhayVAshokan _a

question _t

**Comment by gaagul** [comment]
@ajmaln I will look into the possibilities and let you know.

**Comment by gaagul** [comment]
@gaagul _a
