### ISSUE TITLE
Image width is overflowing the editor container

### ISSUE THREAD

**Issue by philson-philip** [neetozone/neeto-editor#902]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/4912

@AbhayVAshokan _a

**Comment by AbhayVAshokan** [comment]
@gaagul _a can you check the feasibility of restricting the width of the image till the width of the parent?

**Comment by gaagul** [comment]
> @gaagul _a can you check the feasibility of restricting the width of the image till the width of the parent?

This is a style change i could come up with, which does not affect the resizing and aspect ratio of images :https://gaagul-gigi.neetorecord.com/watch/ff24b315-9141-4236-a2f8-71339822c268

**Comment by AbhayVAshokan** [comment]
@gaagul _a https://vimeo.com/871892075/0be5491264?share=copy

**Comment by gaagul** [comment]
> @gaagul _a https://vimeo.com/871892075/0be5491264?share=copy

I will take a detailed look into the possibilities, and will give you updates.
