### ISSUE TITLE
Add data-cy to slash active fixed menu active border

### ISSUE THREAD

**Issue by Prasannams97** [neetozone/neeto-editor#927]
|     Element                 |         Current Selector                  |
|---------------------|---------------------------------|
| neetoEditorActiveBorder     | "[class='ProseMirror neeto-editor slash-active fixed-menu-active border attachments-active editor-content__wrapper neeto-kb-new-article__container']" |

**Comment by AbhayVAshokan** [comment]
@gaagul _a
