### ISSUE TITLE
[neeto-kb-frontend/production] TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#931]
Ref: https://github.com/bigbinary/neeto-kb-web/issues/4982

@gaagul _a

**Comment by AbhayVAshokan** [comment]
This issue is not reproducible. I had a call with Nitin to understand what was done to cause the issue. Repeating the same does not cause the issue now. Closing this now. I will look at it if it occurs again.
