### ISSUE TITLE
Handle entering emoji in a better way

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#933]
https://neerajsingh0101.neetorecord.com/watch/58205eb2-6e1d-4012-8280-839cb632536f

**Comment by AbhayVAshokan** [comment]
@gaagul _a can you please check. minor _t

**Comment by gaagul** [comment]
Moving this issue to neeto-chat-web: https://github.com/bigbinary/neeto-chat-web/issues/8949, Will be taken up once latest version of neetoEditor is released.
