### ISSUE TITLE
Add data-cy to done and cancel button on clicking link button and edit and unlink button

### ISSUE THREAD

**Issue by yatharthvij** [neetozone/neeto-editor#944]
Current selector: For done button: ".neeto-ui-btn neeto-ui-btn--style-primary" and for cancel button: ".neeto-ui-btn neeto-ui-btn--style-text"
Ref: 
<img width="1440" alt="Screenshot 2023-11-20 at 9 46 11 PM" src="https://github.com/bigbinary/neeto-editor/assets/75108777/bd2d8204-f6d0-4b3c-9632-2d3197545f23">

Current selector: For edit button: ".neeto-ui-btn ne-link-popover__option-button neeto-ui-btn--style-link" and for unlink button: ".neeto-ui-btn ne-link-popover__option-button neeto-ui-btn--style-link"
Ref:
<img width="1440" alt="Screenshot 2023-11-20 at 9 56 21 PM" src="https://github.com/bigbinary/neeto-editor/assets/75108777/e1789090-2bc0-4ad0-b1aa-f458f04843ef">

**Comment by AbhayVAshokan** [comment]
@gaagul _a
