### ISSUE TITLE
Add 'anyCase' to translations

### ISSUE THREAD

**Issue by sritabh** [neetozone/neeto-editor#949]
Ref: https://github.com/bigbinary/neeto-engineering-web/issues/601

All dynamic part of the translation are now lowercased, so if there is any instance we need to preserve the case please add 'anyCase' formatter to it
eg: "Create {{entity, anyCase}}"

**Comment by AbhayVAshokan** [comment]
There are no dynamic translations that need to be any cased. Closing this issue.
