### ISSUE TITLE
Formatting issue with codeblock

### ISSUE THREAD

**Issue by neerajsingh0101** [neetozone/neeto-editor#952]
https://www.loom.com/share/6892459ed4a541ab912a6326f7512a93

**Comment by gaagul** [comment]
@AbhayVAshokan I have gone through the documentation of tiptap and also some discussiuons, also researched on how substack has implemented this same feature using tiptap, these are my findings: https://gaagul-gigi.neetorecord.com/watch/baff2271-ae90-43f9-bf03-8473aeaf1cd2, Please share you thoughts on this.

**Comment by AbhayVAshokan** [comment]
Sadly, this is the default behavior. Even Notion has the same behavior. TipTap has not yet addressed this concern: https://github.com/ueberdosis/tiptap/issues/931
