### ISSUE TITLE
Linkify the text when user types in a link.

### ISSUE THREAD

**Issue by deepakjosp** [neetozone/neeto-editor#966]
Original issue ref - https://github.com/bigbinary/neeto-chat-web/issues/8936

https://monosnap.com/file/rD01tu484PUlNDhXroCjVvwomkcC5I

@AbhayVAshokan  _a could you please check?

**Comment by AbhayVAshokan** [comment]
@gaagul _a

**Comment by gaagul** [comment]
@AbhayVAshokan _a These are my findings, https://gaagul-gigi.neetorecord.com/recordings/8b6fa9b7-9358-4f1e-8072-70f4817dff08, Please let me know your thoughts.
