### ISSUE TITLE
Add aria-* labels to make editor more accessible

### ISSUE THREAD

**Issue by VarunSriram99** [neetozone/neeto-editor#969]
While working on neeto-editor with Playwright, we noticed that a few commands such as [fill](https://playwright.dev/docs/next/api/class-locator#locator-fill) were not working. This was because the editor did not fall under the roles of `<input>` or `<textarea>` and is not a `[contenteditable]` tag. The same can be an issue with accessibility as screen readers might not identify the editor to be a text field. Adding the proper aria labels should help resolve this issue and improve the testing experience as well.

@AbhayVAshokan _a
enhancement _t

**Comment by AbhayVAshokan** [comment]
@gaagul _a
