### ISSUE TITLE
Fix inconsistency between font-size of `<code>` and `<h1>`

### ISSUE THREAD

**Issue by roshanrajeev** [neetozone/neeto-editor#973]
There is an inconsistency between font-size of `<h1>` and `<code>` tags 👇 
<img width="996" alt="Screenshot 2023-12-20 at 8 49 17 AM" src="https://github.com/bigbinary/neeto-editor/assets/52269241/e596ce50-3d84-45aa-acf2-f63e36bf12ec">

---
Increasing font-size of code inside h1 will look much better.
<img width="971" alt="Screenshot 2023-12-20 at 8 48 16 AM" src="https://github.com/bigbinary/neeto-editor/assets/52269241/f8e98a65-e656-48b1-9fd2-a1c294187dab">

---
Rest of the modifiers like italics, underline, strike down, etc works fine. 
**I think this issue applies to other heading tags too.**

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@gaagul _a
