### ISSUE TITLE
Add a utility function to remove empty lines from editor content

### ISSUE THREAD

**Issue by roshanrajeev** [neetozone/neeto-editor#977]
neeto-editor adds a new line using `<p></p>` and nested break tags on `Enter` and `Shift + Enter` respectively. A utility function to remove the empty lines from the ends of the editor content is required.

Ref: https://github.com/bigbinary/neeto-quiz-web/issues/3340

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
Once the PR in neetoQuiz is merged. Let's make similar changes here.
@roshanrajeev _a
