### ISSUE TITLE
Formik Editor not getting re-rendered 

### ISSUE THREAD

**Issue by naufil50** [neetozone/neeto-editor#986]
Formik Editor component from neeto-editor does not get re-rendered with values on state change. I am using it inside Form. Please have a look for more details https://naufil-kharbe.neetorecord.com/watch/68e6ea4e-ae3c-4fcf-8d93-f256c491971e
. Please do let me know if I am missing something or any more details are required from my end

cc: @AbhayVAshokan

**Comment by AbhayVAshokan** [comment]
@naufil50: The `Editor` and `FormikEditor` components are not controlled components. As a result, a change in the state shall not update the content. Can you please try adding a unique `key` to the `FormikEditor` component and LMK this solves the issue? Adding a key will force React to render a separate component for each case.

If not, please use the `setContent` command to update the editor content on selecting another item from the dropdown.
https://neeto-editor.neeto.com/?path=/docs/api-reference-editor-api--page#commands

discussion _t

**Comment by naufil50** [comment]
Used setContent command and its working. Thanks @AbhayVAshokan . Closing this issue.
