### ISSUE TITLE
Issues with neeto-editor

### ISSUE THREAD

**Issue by rishavkr08** [neetozone/neeto-editor#99]
@karthiknmenon _a https://www.loom.com/share/c5c10bb701c040e283da12add0278492

cc: @amaldinesh7 @labeebklatif

**Comment by rishavkr08** [comment]
`.neeto-ui-pane__close` has `position: absolute` but it gets overridden by `.neeto-ui-btn`

**Comment by karthiknmenon** [comment]
@AbhayVAshokan _a Could you please take a loot at this issue?
