### ISSUE TITLE
Attachments and Previews are not working

### ISSUE THREAD

**Issue by sandip-mane** [neetozone/neeto-editor#990]
bug _t
priority _t

https://sandip-mane.neetorecord.com/watch/80e750e0-715b-473a-98f1-de5be322db95

1. Attachments have invalid URLs
2. Previews should be supported for:
    - [ ] Excel
    - [ ] Docs
    - [ ] PDF
    - [ ] Images

**Comment by gaagul** [comment]
@gaagul _a

**Comment by AbhayVAshokan** [comment]
Let us solve the issues with subdomain as the first part of this issue and take up changes related to adding previews for Excel and Docs in https://github.com/bigbinary/neeto-editor/issues/991.

**Comment by gaagul** [comment]
I believe the host app is responsible for the subdomain part, In neetoKb i was able to find : https://github.com/bigbinary/neeto-kb-web/blob/70d1dfe251a1e6fbb36d54035233be96d645fdd4/app/views/api/v1/admin/articles/_attachment.json.jbuilder#L4

@AbhayVAshokan , @sandip-mane , Please let me know you thoughts on this.

**Comment by sandip-mane** [comment]
Found similar implementation in neetoDesk:

https://github.com/bigbinary/neeto-desk-web/blob/0386303d44fc96f4d885e3b939309ad3eb943884/app/carriers/attachment_carrier.rb#L34-L36

I will create independent issues in neetoDesk and neetoKB.

However, should we standardize it so that this does not happen in future?

**Comment by gaagul** [comment]
> However, should we standardize it so that this does not happen in future?

I couldn't locate any specific initializers for Active Storage. If there's an alternative method it would be great.

**Comment by sandip-mane** [comment]
We can move the AttachmentCarrier to neetoCommons and then use that from all the apps.

Before that, we need to see how other neeto apps are using it.

**Comment by gaagul** [comment]
Removing the priority label since the issue with urls are fixed and research is needed for adding previews to:
-  Excel
-  Docs
-  PDF
-  Images

**Comment by sandip-mane** [comment]
@gaagul we can close this issue. We have another one for adding these features. Ref: https://github.com/bigbinary/neeto-editor/issues/991

**Comment by gaagul** [comment]
Closing the issue.
